lib/al/sensor/HitSensor.h
lib/al/util/StringUtil.h

- Fixes a cyclical dependency in HitSensor with LiveActor
- Reclassifies _ZN2al16ActorScoreKeeper4initERKNS_9ByamlIterE as mismatched rather than ok
- Fixes mismatch in StringUtil to not inline isEqualString(const char*, const char*)

Fix issues with compilation and some mismatches

---

lib/al/sensor/SensorMsg.h
lib/game/player/PlayerEquipmentUser.h
lib/rs/Sensor.h
src/game/player/CMakeLists.txt
src/game/player/PlayerEquipmentUser.cpp

The ordering of the ``equipmentSensor`` and the ``sourceSensor`` got a bit confusing - I hope I got it right.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/6)

`game/player`: Implement `PlayerEquipmentUser`

---

lib/game/judge/IJudge.h
lib/rs/Judge.h
src/rs/CMakeLists.txt
src/rs/Judge.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/9)

`game/judge`: Add `IJudge` and utility functions

---

lib/al/player/PlayerActorBase.h
src/al/player/PlayerActorBase.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/11)

`al/player`: Set `getPlayerCollision()` return type to `IUsePlayerCollision`

---

lib/al/LiveActor/ActorPoseKeeper.h
lib/al/util/LiveActorUtil.h
lib/al/util/MathUtil.h
lib/al/util/OtherUtil.h
src/al/util/LiveActorUtil.cpp
src/game/objects/Mofumofu/MofumofuWarpHole.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/12)

`al`: add ActorPoseKeeper header and some utility functions

---

lib/al/player/PlayerActorBase.h
lib/game/player/PlayerInfo.h
src/al/player/PlayerActorBase.cpp
src/game/player/CMakeLists.txt
src/game/player/PlayerInfo.cpp

I believe I got all of the fields right...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/8)

`game/player`: Add `PlayerInfo`

---

.github/workflows/compile-check.yml
.github/workflows/lint.yml
README.md
lib/al/include/Library/LiveActor/SubActorKeeper.h
lib/al/include/Library/Math/MathAngleUtil.h
lib/al/include/Library/Matrix/MatrixUtil.h
lib/al/src/Library/Area/AreaShapeCube.cpp
lib/al/src/Library/LiveActor/ActorMovementFunction.cpp
lib/al/src/Library/Obj/PartsModel.cpp
src/Scene/ProjectAppearSwitchFactory.cpp

First up, the simpler workflow: Running a clang-format action on all game-related files, both on push and for pull requests.
Second, a more complex workflow to verify CSV and actual decompile lining up. It starts off by just straight up failing when `W` functions are found in a PR - those should never end up in the repo, so don't continue here. Similar to the `progress` workflow, it will then set up a development environment, this time however running the full setup script, including analyzing the game binaries. To make that possible, I've uploaded an unpacked 1.0 binary to my server, hiding it with a password. Finally, it runs the `tools/check` binary, and only completes the workflow successfully, if no functions are listed as having a different state than listed. After fiddling around …

Add workflow for linting and function state verification

---

.github/workflows/clean-headers.yml
.github/workflows/copy-headers.yml
.github/workflows/progress.yml

There still seems to be some issue remaining, but this should hopefully at least show more debug information, allowing it to be fixed ... eventually.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/22)

Attempts to fix some issues with workflow

---

lib/al/src/Library/Yaml/ByamlData.cpp
lib/al/src/Library/Yaml/ByamlHeader.cpp
lib/al/src/Library/Yaml/ByamlIter.cpp
lib/al/src/Library/Yaml/Writer/ByamlWriter.cpp
lib/al/src/Library/Yaml/Writer/ByamlWriterData.cpp
lib/al/src/Library/Yaml/Writer/ByamlWriterStringTable.cpp

As `byaml` was one of the first areas I looked into when getting started on this project, I didn't have a lot of experience - thus some avoidable mistakes/mismatches were part of the codebase.
Here, I went over all functions marked as minor or major mismatches in the function list, and tried matching them again - improving or matching most.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/19)

al/Lib/Yaml: Fix some mismatches

---

lib/al/include/Library/Action/ActorActionKeeper.h
lib/al/include/Library/Audio/System/AudioSystemInfo.h
lib/al/include/Library/Bgm/BgmDirector.h
lib/al/include/Library/Bgm/BgmFunction.h
lib/al/include/Library/Bgm/BgmKeeper.h
lib/al/include/Library/Bgm/BgmLineFunction.h
lib/al/include/Library/LiveActor/ActorAnimFunction.h
lib/al/include/Library/Model/ModelCtrl.h
lib/al/include/Library/Nerve/NerveExecutor.h
lib/al/include/Library/Resource/Resource.h
lib/al/include/Library/Resource/ResourceHolder.h
lib/al/include/Project/Action/ActionAnimCtrl.h
lib/al/include/Project/Action/ActionEffectCtrl.h
lib/al/include/Project/Action/ActionFlagCtrl.h
lib/al/include/Project/Action/ActionFunction.h
lib/al/include/Project/Bgm/BgmInfo.h
lib/al/src/Library/Action/ActorActionKeeper.cpp
lib/al/src/Library/Bgm/BgmKeeper.cpp
lib/al/src/Project/Action/ActionFunction.cpp
lib/al/src/Project/Bgm/BgmInfo.cpp

yes
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24)

Add some Action and Bgm headers

---

src/Scene/SceneObjFactory.cpp
src/Scene/SceneObjFactory.h

This PR mostly adds the `SceneObjID` enum. This list was compiled by @tetraxile, the suggestion to create an enum was done by @fruityloops1.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/26)

Scene: Add SceneObjFactory

---

lib/al/include/Library/Network/AccountHolder.h
lib/al/src/Library/Network/AccountHolder.cpp

this pr adds `AccountHolder` definition and it's implementation
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/32)

AccountHolder functions

---

lib/al/include/Library/Area/SwitchAreaDirector.h
lib/al/include/Library/Camera/CameraDirector.h
lib/al/include/Library/Controller/PadRumbleDirector.h
lib/al/include/Library/Draw/GraphicsSystemInfo.h
lib/al/include/Library/Effect/EffectSystem.h
lib/al/include/Library/Execute/ExecuteSystemInitInfo.h
lib/al/include/Library/Execute/ExecuteTableHolderUpdate.h
lib/al/include/Library/Execute/IUseExecutor.h
lib/al/include/Library/LiveActor/LiveActorGroup.h
lib/al/include/Library/LiveActor/LiveActorKit.h
lib/al/include/Library/Model/ModelDisplayListController.h
lib/al/include/Library/Model/ModelDrawBufferUpdater.h
lib/al/include/Library/Model/ModelGroup.h
lib/al/include/Library/Nature/NatureDirector.h
lib/al/include/Library/Obj/DynamicDrawActor.h
lib/al/include/Library/Resource/ActorResourceHolder.h
lib/al/include/Library/Scene/ItemDirectorBase.h
lib/al/include/Library/Screen/ScreenPointDirector.h
lib/al/include/Library/Shader/ForwardRendering/ShaderHolder.h
lib/al/include/Library/Shadow/ShadowDirector.h
lib/al/include/Library/Stage/StageSwitchKeeper.h
lib/al/include/Project/Clipping/ClippingDirector.h
lib/al/include/Project/Execute/ExecuteAsyncExecutor.h
lib/al/include/Project/Gravity/GravityHolder.h
lib/al/include/Project/HitSensor/HitSensorDirector.h
lib/al/src/Library/LiveActor/LiveActorKit.cpp

While this class itself is not particularly large, it required specifying/stubbing a bunch of `Director` headers, which is the main part of this PR.
Please note that I have (for the most part) not added the *contents* of the class, but the entire list of functions. In cases where this is not the case, a comment is added (`incomplete/missing`).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/28)

`al/Library/LiveActor`: Decompile LiveActorKit

---

lib/al/include/Library/HitSensor/HitSensorKeeper.h

@Sanae6 reported a few issues with the existing header file, so ... while we're at it, just fix/add everything and call this header "done".
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/36)

Library/HitSensor: Complete HitSensorKeeper.h

---

src/Player/CollisionShapeInfo.cpp
src/Player/CollisionShapeInfo.h

Pretty simple class, not much going on here. Will be used in another PR soon :tm:.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/39)

Player: Add CollisionShapeInfoBase

---

lib/al/include/Library/LiveActor/ActorDrawFunction.h
lib/al/include/Library/LiveActor/ActorInitFunction.h
lib/al/include/Library/Obj/AllDeadWatcher.h
lib/al/include/Library/Stage/StageSwitchKeeper.h
lib/al/src/Library/Obj/AllDeadWatcher.cpp

This PR adds `AllDeadWatcher` definition and it's implementation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/41)

AllDeadWatcher functions

---

lib/al/include/Library/Event/SceneEventFlowMsg.h
lib/al/src/Library/Event/SceneEventFlowMsg.cpp

This PR adds `SceneEventFlowMsg` definition and it's implementation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/45)

SceneEventFlowMsg functions

---

lib/al/include/Library/LiveActor/LiveActorUtil.h
src/Amiibo/HelpAmiiboExecutor.cpp
src/Amiibo/HelpAmiiboExecutor.h
src/Amiibo/ItemAmiiboKoopa.cpp
src/Amiibo/ItemAmiiboKoopa.h
src/Boss/Mofumofu/MofumofuWarpHole.cpp
src/Util/Sensor.h

Small classes that initiate work on `src/Amiibo`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/50)

Amiibo: Implement HelpAmiiboExecutor & ItemAmiiboKoopa

---

lib/al/include/Library/Layout/LayoutActionFunction.h
lib/al/include/Library/Layout/LayoutActorUtil.h
lib/al/include/Library/Layout/LayoutInitInfo.h
src/Layout/BootLayout.cpp
src/Layout/BootLayout.h
src/Layout/ButtonMiiverse.cpp
src/Layout/ButtonMiiverse.h

Adds `BootLayout` `ButtonMiiverse` from https://github.com/odyssey-modding/odyssey/pull/11
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/56)

Layout: Implement BootLayout and ButtonMiiverse

---

lib/al/include/Library/Math/MathUtil.h
src/Player/PlayerCounterGetCoin.cpp
src/Player/PlayerCounterGetCoin.h

Very small unused class.
I had to add `al::converge` functions here, and I've placed them in `MathUtil.h` as that seems to be full of the unorganized stuff. That being said, I'm pretty sure we agreed on un-splitting `MathUtil.h` in Discord, so that should happen at some point.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/58)

Player: Implement PlayerCounterGetCoin

---

lib/al/include/Library/LiveActor/SubActorKeeper.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/65)

Fix affected file from updated clang-format workflow

---

lib/al/include/Library/Memory/HeapUtil.h
lib/al/include/Library/System/SystemKit.h
lib/al/include/Project/Memory/MemorySystem.h
lib/al/src/Library/Memory/HeapUtil.cpp
src/System/ProjectInterface.h

This PR adds `HeapUtil` functions and a header for `MemorySystem`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/73)

HeapUtil functions

---

src/Player/PlayerWallActionHistory.cpp
src/Player/PlayerWallActionHistory.h
src/Util/PlayerCollisionUtil.h

This class keeps track of the last `Jump` and `Leave` position and normal of a `WallAction` (=Slide, Jump).
As `update` is called on every frame, the information will be `reset` as soon as the Player touches the ground.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/74)

Player: Implement PlayerWallActionHistory

---

lib/al/include/Library/Math/VectorUtil.h
src/Player/PlayerCarryKeeper.h
src/Player/PlayerHackKeeper.h
src/Player/PlayerInput.h
src/Player/PlayerJudgeTalkGround.cpp
src/Player/PlayerJudgeTalkGround.h
src/Player/PlayerStateWait.h
src/Util/PlayerCollisionUtil.h

Had to do a duplicate PR since I'm bad at git: Implemented all functions for **PlayerJudgeTalkGround.** Any suggestions on what header should I put the rs declarations in?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/83)

Player: PlayerJudgeTalkGround (retry)

---

src/Player/PlayerJudgeForceRolling.cpp
src/Player/PlayerJudgeForceRolling.h
src/Util/PlayerCollisionUtil.h

When the FloorCollision-Code forces you to roll, then ... you should roll. Simple.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/84)

Player: Implement PlayerJudgeForceRolling

---

src/Player/PlayerJudgeSameNerve.cpp
src/Player/PlayerJudgeSameNerve.h

A simple judge that just checks whether the given nerve user is currently using the given nerve.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/97)

Player: Implement PlayerJudgeSameNerve

---

src/Player/IUsePlayerHeightCheck.h

Simple header, used for example in `PlayerColliderHakoniwa`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/104)

Player: Add IUsePlayerHeightCheck

---

src/Layout/CoinCollectLayout.cpp
src/Layout/CoinCollectLayout.h

`CoinCollectLayout` is the little pop-up text whenever you collect a purple coin.
decomp.me for `appearCounter` because I'm having trouble using `updatePos()`: https://decomp.me/scratch/qA5ib
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/111)

Layout: Implement `CoinCollectLayout`

---

lib/al/Library/Camera/CameraLimitRailKeeper.h
lib/al/Library/Camera/CameraUtil.h
lib/al/Library/LiveActor/ActorInitInfo.h
lib/al/Library/Obj/CameraRailHolder.cpp
lib/al/Library/Obj/CameraRailHolder.h

This PR adds `CameraRailHolder` functions and a header for `CameraLimitRailKeeper`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/113)

CameraRailHolder functions

---

lib/al/Library/Layout/LayoutActor.h
src/Layout/GaugeAir.cpp
src/Layout/GaugeAir.h

Used by Mario when he's running out of oxygen.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/119)

Layout: Implement `GaugeAir`

---

lib/al/Library/Camera/CameraUtil.h
lib/al/Library/LiveActor/ActorInitFunction.h
lib/al/Library/Obj/CameraWatchPoint.cpp
lib/al/Library/Obj/CameraWatchPoint.h
lib/al/Project/Camera/CameraSubTargetTurnParam.cpp
lib/al/Project/Camera/CameraSubTargetTurnParam.h

This PR adds `CameraWatchPoint` functions and `CameraSubTargetTurnParam` functions
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/121)

Implement `CameraWatchPoint` and `CameraSubTargetTurnParam`

---

Contributing.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/125)

fix broken cheatsheet link in guide

---

lib/al/Library/LiveActor/ActorInitFunction.h
lib/al/Library/LiveActor/SubActorKeeper.cpp
lib/al/Library/Obj/CollisionObj.cpp
lib/al/Library/Obj/CollisionObj.h
lib/al/Library/Obj/PartsFunction.h

This PR adds `CollisionObj` implementation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/123)

Library/Obj: Implement `CollisionObj`

---

lib/al/Library/LiveActor/ActorInitFunction.h
lib/al/Library/Obj/DepthShadowModel.cpp
lib/al/Library/Obj/DepthShadowModel.h

This PR adds `DepthShadowModel` implementation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/127)

Library/Obj: Implement `DepthShadowModel`

---

lib/al/Library/LiveActor/ActorAreaFunction.h
lib/al/Library/LiveActor/ActorInitFunction.h
lib/al/Library/MapObj/FallMapParts.cpp
lib/al/Library/MapObj/FallMapParts.h

This PR adds `FallMapParts` functions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/130)

Library/MapObj: Implement `FallMapParts`

---

lib/al/Library/Audio/System/SimpleAudioUser.h
lib/al/Library/Effect/EffectKeeper.h
lib/al/Library/Item/ItemUtil.h
lib/al/Library/LiveActor/ActorInitFunction.cpp
lib/al/Library/LiveActor/ActorInitFunction.h
lib/al/Library/LiveActor/SubActorKeeper.cpp
lib/al/Library/LiveActor/SubActorKeeper.h
lib/al/Library/MapObj/BreakMapPartsBase.cpp
lib/al/Library/MapObj/BreakMapPartsBase.h
lib/al/Library/Obj/PartsFunction.h
lib/al/Library/Stage/StageSwitchKeeper.h
lib/al/Library/Stage/StageSwitchUtil.h

This PR adds `BreakMapPartsBase` functions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/134)

Library/MapObj: Implement `BreakMapPartsBase`

---

lib/al/Library/LiveActor/ActorInitFunction.h
lib/al/Library/MapObj/ChildStep.cpp
lib/al/Library/MapObj/ChildStep.h

This PR adds `ChildStep` functions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/136)

Library/MapObj: Implement `ChildStep`

---

lib/al/Library/Collision/KCollisionServer.h

This adds the header for `al::KCollisionServer`, including its functions, member variables and helper structs. I've tried to name the parameters of the more obvious functions, the other parameters will be named once their respective function will be decompiled.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/106)

Library/Collision: Add KCollisionServer

---

src/Layout/CounterLife.cpp
src/Layout/CounterLife.h
src/System/GameDataFunction.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/144)

CounterLife

---

lib/al/Library/Clipping/ViewIdHolder.cpp
lib/al/Library/Execute/ActorExecuteInfo.cpp
lib/al/Library/Execute/ActorExecuteInfo.h
lib/al/Library/Execute/ExecuteDirector.cpp
lib/al/Library/Execute/ExecuteDirector.h
lib/al/Library/Execute/ExecuteOrder.h
lib/al/Library/Execute/ExecuteRequestKeeper.h
lib/al/Library/Execute/ExecuteSystemInitInfo.h
lib/al/Library/Execute/ExecuteTable.h
lib/al/Library/Execute/ExecuteTableHolderDraw.h
lib/al/Library/Execute/ExecuteTableHolderUpdate.h
lib/al/Library/Execute/ExecuteTablesImpl.h
lib/al/Library/Execute/ExecutorListBase.h
lib/al/Library/Execute/IUseExecutor.h
lib/al/Library/Execute/LayoutExecuteInfo.h
lib/al/Project/Execute/ExecuteAsyncExecutor.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/150)

clean up various Execute headers

---

lib/al/Library/LiveActor/ActorInitFunction.h
lib/al/Library/MapObj/FloaterMapParts.cpp
lib/al/Library/MapObj/FloaterMapParts.h
src/Scene/ProjectActorFactory.cpp

This PR adds `FloaterMapParts` functions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/147)

Library/MapObj: Implement `FloaterMapParts`

---

lib/al/Library/Camera/CameraTargetBase.cpp
lib/al/Library/Camera/CameraTargetBase.h

Quick, simple, easy. Just a base class which is used to create some actual targets, with a common base type and interface.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/151)

Library/Camera: Implement `CameraTargetBase`

---

lib/al/Library/Camera/CameraTicketId.cpp
lib/al/Library/Camera/CameraTicketId.h
lib/al/Library/Placement/PlacementId.h

This is a small helper class to store some camera-related details. `CameraTicket`s are afaik those things that can be configured/created in stage files that define different modes, angles and other options, so this `TicketId` is only the "identification" part of it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/152)

Library/Camera: Implement `CameraTicketId`

---

lib/al/Library/Camera/CameraTicket.h
lib/al/Library/Camera/CameraTicketId.h
lib/al/Library/Camera/SpecialCameraHolder.cpp
lib/al/Library/Camera/SpecialCameraHolder.h

Doing small classes is fun! This one just holds a bunch of `CameraTicket`s relating to specific entrances.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/161)

Library/Camera: Implement `SpecialCameraHolder`

---

src/Item/Shine.h

Adding the header for `Shine` including all function definitions. Required for #156.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/163)

Item: Add `Shine`

---

lib/al/Library/LiveActor/ActorInitFunction.h

This PR changes the name of the last parameter in the `initNerveAction` function and add `initNerve` function in the correct header.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/176)

Library/LiveActor: Refactor `ActorInitFunction`

---

lib/al/Library/MapObj/GateMapParts.cpp
lib/al/Library/MapObj/GateMapParts.h
lib/al/Library/Stage/StageSwitchKeeper.h
src/Scene/ProjectActorFactory.cpp

This PR adds `GateMapParts` functions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/173)

Library/MapObj: Implement `GateMapParts`

---

src/Util/ItemUtil.h

Adding the header for `ItemUtil` including all function definitions. Required for #156.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/166)

Util: Add `ItemUtil`

---

lib/al/Library/Area/AreaObj.h
lib/al/Library/File/FileLoader.h
lib/al/Library/LiveActor/CreateActorFunction.h
lib/al/Library/LiveActor/LiveActorUtil.h
lib/al/Library/Placement/PlacementFunction.h
lib/al/Library/Sequence/Sequence.cpp
lib/al/Library/Sequence/Sequence.h
lib/al/Library/Wipe/WipeHolder.h
src/Scene/ProjectActorFactory.cpp
src/Sequence/ChangeStageInfo.h
src/Sequence/HakoniwaSequence.h
src/System/GameDataFunction.h
src/System/GameDataHolder.h

This PR changes some headers and adds some new ones. All the new headers are modified versions of galaxy mod headers with extra info and parameter names.
I also moved `al::Sequenece::isDisposable` into a cpp file since it shouldn't be in a header.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/174)

More mod headers

---

lib/al/Library/Nature/NatureUtil.h
src/Player/PlayerAreaChecker.cpp
src/Player/PlayerAreaChecker.h
src/System/GameDataHolderAccessor.h
src/Util/Area.h
src/Util/ObjUtil.h

Implementing a new random class, this time `PlayerAreaChecker`. It just forwards a bunch of calls to `al` with known constant, area names, or applies a bit of math beforehand (project next frame and check).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/167)

Player: Implement `PlayerAreaChecker`

---

lib/al/Library/Math/VectorUtil.h
src/Enemy/SenobiLeaf.cpp
src/Enemy/SenobiLeaf.h

This is the first of multiple PRs I'm doing for @GRAnimated. All the implementation was done by Gra, I just fixed the formatting. 
`SenobiLeaf::registerToHost` mismatches because of a regswap: https://decomp.me/scratch/4HU85 (The other stuff are just decomp.me errors). I tried a lot of stuff, but wasn't able to fix it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/177)

Enemy: Implement SenobiLeaf (By GRA)

---

lib/al/Library/LiveActor/ActorCollisionFunction.h
lib/al/Library/LiveActor/ActorSensorMsgFunction.h
src/Boss/Mofumofu/MofumofuWarpHole.cpp
src/MapObj/AnagramAlphabetCharacter.cpp
src/MapObj/AnagramAlphabetCharacter.h
src/Player/HackerJudge.h
src/Util/Hack.h
src/Util/Sensor.h

In June of 2023, this actor was the most challenging thing I had worked on at that point. I made many mismatches then and this PR should rectify that.
I'm not sure when, but I guess I also fixed a mismatch in `MofumofuWarpHole` on this branch, so enjoy that as well.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/143)

`MapObj`: Finish `AnagramAlphabetCharacter`

---

lib/al/Library/Nerve/NerveStateBase.cpp
lib/al/Library/Nerve/NerveStateBase.h
lib/al/Library/Wipe/WipeSimple.h
src/Scene/StageSceneStateEndSeparatePlay.cpp
src/Scene/StageSceneStateEndSeparatePlay.h
src/Scene/StageSceneStatePauseMenu.h
src/Scene/StageSceneStateStartSeparatePlay.cpp
src/Scene/StageSceneStateStartSeparatePlay.h
src/Util/SpecialBuildUtil.h

Another PR I'm doing for @GRAnimated. This one implements two `StageScene` states and adds some headers required for them
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/179)

Scene: Implement StageSceneStateStartSeparatePlay and StageSceneStateEndSeparatePlay (By GRA)

---

lib/al/Library/LiveActor/ActorInitFunction.h
lib/al/Library/MapObj/OneMeshFixMapParts.cpp
lib/al/Library/MapObj/OneMeshFixMapParts.h
src/Scene/ProjectActorFactory.cpp

This PR adds `OneMeshFixMapParts` functions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/191)

Library/MapObj: Implement `OneMeshFixMapParts`

---

lib/al/Library/LiveActor/LiveActorUtil.h
src/Amiibo/ItemAmiiboKoopa.cpp
src/Boss/Mofumofu/MofumofuWarpHole.cpp
src/Util/PlayerUtil.h

Well, this was placed in the wrong file back in 2021 - it should be moved to the right place instead.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/192)

al: Move `rs::getPlayerPos` to game

---

lib/al/Library/LiveActor/ActorInitFunction.h
lib/al/Library/MapObj/RollingCubeMapParts.cpp
lib/al/Library/MapObj/RollingCubeMapParts.h
lib/al/Library/Math/MathAngleUtil.h
lib/al/Library/Obj/PartsModel.cpp
lib/al/Project/Joint/RollingCubePoseKeeper.h
src/Scene/ProjectActorFactory.cpp

This PR adds `RollingCubeMapParts` functions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/194)

Library/MapObj: Implement `RollingCubeMapParts`

---

lib/al/Library/Movement/RailMoveMovement.cpp
lib/al/Library/Movement/RailMoveMovement.h
lib/al/Library/Nerve/NerveStateBase.cpp
lib/al/Library/Nerve/NerveStateBase.h
lib/al/Library/Rail/RailUtil.h
tools/check-format.py

This PR adds `RailMoveMovement` functions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/180)

Library/Movement: Implement `RailMoveMovement`

---

lib/al/Library/Collision/CollisionPartsKeeperUtil.h
lib/al/Library/Collision/KCollisionServer.h
lib/al/Library/LiveActor/ActorMovementFunction.h
lib/al/Library/MapObj/SurfMapParts.cpp
lib/al/Library/MapObj/SurfMapParts.h
lib/al/Library/Math/VectorUtil.h
src/Scene/ProjectActorFactory.cpp

This PR adds `SurfMapParts` functions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/195)

Library/MapObj: Implement `SurfMapParts`

---

lib/al/Library/Area/SwitchKeepOnAreaGroup.h
lib/al/Library/Area/SwitchOnAreaGroup.h
lib/al/Library/Fluid/IUseFluidSurface.h
lib/al/Library/Fluid/RippleCtrl.h
lib/al/Library/KeyPose/KeyPoseKeeper.h
lib/al/Library/LiveActor/ActorAreaFunction.h
lib/al/Library/MapObj/KeyMoveMapParts.cpp
lib/al/Library/MapObj/KeyMoveMapParts.h
lib/al/Library/Stage/StageSwitchKeeper.h
src/Scene/ProjectActorFactory.cpp

This PR adds `KeyMoveMapParts` functions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/198)

Library/MapObj: Implement `KeyMoveMapParts`

---

lib/al/Library/LiveActor/ActorDrawFunction.h
lib/al/Library/LiveActor/ActorInitFunction.h
lib/al/Library/LiveActor/LiveActorGroup.h
lib/al/Library/MapObj/KeyMoveMapParts.h
lib/al/Library/MapObj/KeyMoveMapPartsGenerator.cpp
lib/al/Library/MapObj/KeyMoveMapPartsGenerator.h
src/Scene/ProjectActorFactory.cpp

This PR adds `KeyMoveMapPartsGenerator` functions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/201)

Library/MapObj: Implement `KeyMoveMapPartsGenerator`

---

lib/al/Library/Anim/DitherAnimator.h
lib/al/Library/MapObj/BackHideParts.cpp
lib/al/Library/MapObj/BackHideParts.h
lib/al/Library/Model/ModelKeeper.h
src/Scene/ProjectActorFactory.cpp

This PR adds `BackHideParts`, `BackHideDitherAnimator` and `DitherAnimator` functions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/202)

Library/MapObj: Implement `BackHideParts` and `BackHideDitherAnimator`, Library/Anim: Implement `DitherAnimator`

---

lib/al/Library/Collision/CollisionParts.h

Just adding more member variables to this type according to my current research. Inspired by some message in the past asking for a header of this type.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/199)

Library/Collision: Add more `CollisionParts`-members

---

.devcontainer/Dockerfile
README.md

This PR downgrade `libtinfo5` with an available version.
Fix: #205
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/206)

Dependencies: Downgrade `libtinfo5`

---

lib/al/Library/MapObj/ClockMapParts.cpp
lib/al/Library/MapObj/ClockMapParts.h
src/MapObj/SubActorLodFixPartsScenarioAction.h
src/Scene/ProjectActorFactory.cpp

This PR adds `ClockMapParts` functions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/204)

Library/MapObj: Implement `ClockMapParts`

---

lib/al/Library/MapObj/RollingCubeMapParts.cpp
lib/al/Library/MapObj/RotateMapParts.cpp
lib/al/Library/MapObj/RotateMapParts.h
lib/al/Library/Math/Axis.h
lib/al/Library/Math/MathAngleUtil.h
src/Scene/ProjectActorFactory.cpp

This PR adds `RotateMapParts` functions and introduce a new enum `Axis`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/212)

Library/MapObj: Implement `RotateMapParts`

---

lib/al/Library/Nfp/NfpFunction.h
src/Amiibo/HelpAmiiboExecutor.h
src/Amiibo/HelpAmiiboYoshi.cpp
src/Amiibo/HelpAmiiboYoshi.h
src/Player/Yoshi.h

First contribution. I implemented this small class to learn how to contribute here.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/215)

amiibo: Implement HelpAmiiboYoshi

---

CMakeLists.txt

This PR fix #230
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/231)

dev: Fix `NN_` versions in `CMakeLists.txt`

---

src/Util/ExternalForceKeeper.cpp
src/Util/ExternalForceKeeper.h
src/Util/SensorMsgFunction.h

Needed by CoinCollectEmpty. Thanks to ALEX for fixing receiveMsg since I couldn't make it to match.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/228)

Util: Implement `ExternalForceKeeper`

---

lib/al/Library/Nerve/NerveStateBase.h
src/Item/CoinStateCountUp.cpp
src/Item/CoinStateCountUp.h

This one is used by CoinCollectEmpty
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/226)

Item: Implement `CoinStateCountUp`

---

src/Amiibo/SearchAmiiboDataTable.cpp
src/Amiibo/SearchAmiiboDataTable.h

Not sure why it wasn't done this way. As far as I'm aware new does initialize the data. This removes the TODO from this file.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/232)

amiibo: Fix `SearchAmiiboDataTable`

---

lib/al/Library/Nerve/NerveStateBase.h
src/Item/CoinCollectHintState.cpp

This is used by CoinCollect2D and CoinCollectDummy
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/223)

Item: Implement `CoinCollectHintState`

---

src/MapObj/Doshi.h
src/MapObj/DoshiStateWanderBossBattle.cpp
src/MapObj/DoshiStateWanderBossBattle.h

Nothing particularly interesting in this one. Just a small and simple class to implement today.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/235)

MapObj: Implement `DoshiStateWanderBossBattle`

---

src/MapObj/AppearSwitchSave.h
src/MapObj/CapSwitch.cpp
src/MapObj/CapSwitch.h
src/Player/CapTargetInfo.h
src/Scene/ProjectActorFactory.cpp
src/Util/PlayerUtil.h
src/Util/Sensor.h

Implements `CapSwitch`, more commonly known as a Cap Switch.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/242)

MapObj: Implement `CapSwitch`

---

src/Layout/HardIconParts.cpp
src/Layout/HardIconParts.h

What's this even used for?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/248)

Layout: Implement `HardIconParts`

---

src/Layout/LoadLayoutCtrl.cpp
src/Layout/LoadLayoutCtrl.h

Super useful class that gets used everywhere in the game. It's like essential to the game's functionality and fun actually.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/249)

Layout: Implement `LoadLayoutCtrl`

---

src/MapObj/LavaPan.cpp
src/MapObj/LavaPan.h

It's the big pot at the top of the mountain in Luncheon Kingdom, sometimes
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/254)

MapObj: Implement `LavaPan`

---

src/Layout/AmiiboNpcLayout.cpp
src/Layout/AmiiboNpcLayout.h

Implements `AmiiboNpcLayout`. I believe it's the layout used when you hold down D-PAD right ingame.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/247)

Layout: Implement `AmiiboNpcLayout`

---

lib/al/Library/Play/Layout/SimpleLayoutAppearWait.cpp
lib/al/Library/Play/Layout/SimpleLayoutAppearWaitEnd.cpp
lib/al/Library/Play/Layout/SimplePopupMessageLayout.cpp
src/Enemy/EnemyCap.cpp
src/Enemy/EnemyStateDamageCap.cpp
src/Enemy/EnemyStateHackStart.cpp
src/Enemy/EnemyStateReset.cpp
src/Enemy/EnemyStateReviveInsideScreen.cpp
src/Enemy/EnemyStateRunAway.cpp
src/Enemy/EnemyStateWander.cpp
src/Layout/FilterFly.cpp
src/Layout/FilterScope.cpp
src/MapObj/AnagramAlphabetCharacter.cpp
src/Player/Player.cpp
tools/check-format.py

Solves #255
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/256)

lint: Check for uses of NERVE_MAKE

---

lib/al/Library/Area/AreaObj.h

Seems like those were partially missing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/241)

Library/Area: Add `virtual` to `AreaObj`-functions

---

tools/check-format.py

Fixes regex issue with small strings
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/265)

lint: Fix issue with common_string_finder

---

lib/al/Library/LiveActor/ActorInitInfo.h
lib/al/Library/Stage/StageResourceList.cpp
lib/al/Library/Stage/StageResourceList.h

Needed by CoinRotateCalculator.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/261)

Library/Stage: Implement `StageSyncCounter`

---

lib/al/Library/LiveActor/SubActorKeeper.h
lib/al/Library/MapObj/SubActorLodExecutor.cpp
lib/al/Library/MapObj/SubActorLodExecutor.h
lib/al/Library/Model/ModelShapeUtil.h

This PR adds `SubActorLodExecutor` functions
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/233)

Library/MapObj: Implement `SubActorLodExecutor`

---

lib/al/Library/Base/StringUtil.cpp
lib/al/Library/Base/StringUtil.h
lib/al/Project/Action/ActionFlagCtrl.cpp

This PR add some `StringUtil` functions
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/264)

Library/Base: Implement some `StringUtil` functions

---

lib/al/Library/Nature/NatureDirector.h
lib/al/Library/Nature/NatureUtil.h
src/Item/CoinCollectEmpty.cpp
src/Item/CoinCollectEmpty.h
src/Item/CoinRotateCalculator.h
src/Util/ShadowUtil.h

Finally this commit is small enough. CoinCollectEmpty is used by CoinCollect.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/266)

Item: Implement `CoinCollectEmpty`

---

lib/al/Library/Collision/CollisionPartsTriangle.h
lib/al/Library/Nerve/NerveSetupUtil.h
src/Layout/DecideIconLayout.h
src/Scene/HintPhotoLayoutHolder.cpp
src/Scene/HintPhotoLayoutHolder.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/225)

Scene: Implement `HintPhotoLayoutHolder`

---

src/Layout/TestFilterGlasses.cpp
src/Layout/TestFilterGlasses.h

Used by the Moe-Eye capture in Sand Kingdom.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/273)

Layout: Implement `TestFilterGlasses`

---

src/Layout/CoinCounter.cpp
src/Layout/CoinCounter.h
src/Util/StageLayoutFunction.h

This used by StageSceneLayout. Seems to control the coin count animation. It also took quite a bit of attempts to make it fully match.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/269)

Layout: Implement `CoinCounter`

---

CMakeLists.txt
lib/al/Library/Camera/CameraInputHolder.cpp
lib/al/Library/Camera/CameraInputHolder.h

al::CameraInputHolder has been implemented
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/286)

Library/Camera: Implement `CameraInputHolder`

---

lib/al/Library/Nfp/NfpFunction.h
src/Amiibo/HelpAmiiboCountUpCoin.cpp
src/Amiibo/HelpAmiiboCountUpCoin.h
src/Amiibo/HelpAmiiboFunction.h
src/Item/Coin.h
src/Item/Coin2D.h
src/Item/LifeUpItem.h
src/Item/LifeUpItem2D.h
src/Util/PlayerUtil.h

This class seems to spawn between 1-4 coins each time is called. I also got tired of PlayerUtil missing functions so I added all of them at once.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/282)

Amiibo: Implement `HelpAmiiboCountUpCoin`

---

lib/al/Library/Layout/LayoutUtil.h
src/Sequence/HakoniwaSequence.cpp
src/Sequence/HakoniwaSequence.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/285)

Sequence: Implement `HakoniwaSequence::drawMain`

---

src/Npc/VocalMike.cpp
src/Npc/VocalMike.h

Who's vocal Mike? I assume this is the little microphone that Pauline has at the end of the NDC festival.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/279)

Npc: Implement `VocalMike`

---

src/MapObj/VolleyballNet.cpp
src/MapObj/VolleyballNet.h
src/Util/SensorMsgFunction.h

Presumably the volleyball net in Seaside.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/281)

MapObj: Implement VolleyballNet

---

src/Item/CoinBlow.cpp
src/Item/CoinBlow.h
src/Scene/ProjectActorFactory.cpp

How hard will it blow up?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/291)

Item: Implement CoinBlow

---

src/Npc/RaceAudienceNpc.cpp
src/Npc/RaceAudienceNpc.h

I think these are used for the Snow Kingdom race, but they're not hardcoded for it at all. Somebody should use this in a custom map.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/275)

Npc: Implement `RaceAudienceNpc`

---

lib/al/Library/Movement/SwingMovement.cpp
lib/al/Library/Movement/SwingMovement.h

This PR adds `SwingMovement` functions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/290)

Library/Movement: Implement `SwingMovement`

---

lib/al/Library/MapObj/SubActorLodMapParts.cpp
lib/al/Library/MapObj/SubActorLodMapParts.h
src/Scene/ProjectActorFactory.cpp

This PR implement `SubActorLodMapParts` functions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/296)

Library/MapObj: Implement `SubActorLodMapParts`

---

lib/al/Library/Collision/Collider.h
lib/al/Library/Collision/CollisionPartsTriangle.h
lib/al/Library/Effect/EffectSystemInfo.h
src/Amiibo/HelpAmiiboCountUpCoin.cpp
src/Npc/AchievementInfoReader.cpp
src/Player/PlayerContinuousJump.cpp
src/Player/PlayerCounterAfterCapCatch.cpp
src/Player/PlayerCounterAfterUpperPunch.cpp

I just hate looking at them.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/303)

Fix some compilation warnings

---

src/Item/Coin.cpp
src/Item/Coin.h

Cute little class that controls the distance a coin travels after an explosion. Personally this class should go in it's own file. I got some decomp on coin and it will get really big 1000+ lines of code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/295)

Item: Implement `CoinFunction`

---

src/System/RaceRecord.cpp
src/System/RaceRecord.h
src/Util/SequentialUtil.h

Likely the object for koopa freerunning records.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/300)

System: Implement `RaceRecord`

---

lib/al/Library/LiveActor/ActorSensorMsgFunction.h
lib/al/Library/MapObj/SeesawMapParts.cpp
lib/al/Library/MapObj/SeesawMapParts.h
lib/al/Library/Math/MathUtil.h
src/Scene/ProjectActorFactory.cpp

This PR adds `SeesawMapParts` functions except `SeesawMapParts::exeWait`
I gave it a try but I didn't manage to follow the flow of the function.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/293)

Library/MapObj: Implement `SeesawMapParts`

---

lib/al/Library/LiveActor/ActorCollisionFunction.h
src/Player/HackerStateWingFly.cpp
src/Player/HackerStateWingFly.h
src/Util/ObjUtil.h
src/Util/PlayerCollisionUtil.h
src/Util/SensorMsgFunction.h

Defines the behavior of how high a hacker can fly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/302)

Player: Implement HackerStateWingFly

---

src/Player/PlayerActionAirMoveControl.h

This class consists of a lot of really annoying floating-point math, along with at least 20 members that are not easy to figure out the name of. Decompiling this is a project for another day, but we can at least add its header for now, to allow other classes making use of it to be implemented properly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/308)

Player: Add `PlayerActionAirMoveControl`

---

src/Player/PlayerActionTurnControl.h

Another header-only PR with a class filled with unknown members and floating point math.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/309)

Player: Add `PlayerActionTurnControl`

---

src/Player/PlayerJointControlKeeper.h

Another header-only PR. This class doesn't look too bad, it's missing a few required class stubs though - although the major problem is that I'm not interested in decompiling this one. It's just a requirement for some other code I'm looking to contribute soon.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/311)

Player: Add `PlayerJointControlKeeper`

---

lib/al/Library/LiveActor/LiveActorGroup.h
lib/al/Library/MapObj/ConveyerMapParts.cpp
lib/al/Library/MapObj/ConveyerMapParts.h
lib/al/Library/MapObj/ConveyerStep.cpp
lib/al/Library/Stage/StageSwitchKeeper.h
lib/al/Project/LiveActor/ConveyerKeyKeeper.h
src/Scene/ProjectActorFactory.cpp

This PR adds `ConveyerMapParts` functions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/316)

Library/MapObj: Implement `ConveyerMapParts`

---

lib/al/Library/Collision/PartsConnector.h
lib/al/Library/MapObj/VisibleSwitchMapParts.cpp
lib/al/Library/MapObj/VisibleSwitchMapParts.h
src/Scene/ProjectActorFactory.cpp

This PR adds `VisibleSwitchMapParts` functions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/307)

Library/MapObj: Implement `VisibleSwitchMapParts`

---

lib/al/Library/MapObj/SwingMapParts.cpp
lib/al/Library/MapObj/SwingMapParts.h
lib/al/Library/Movement/SwingMovement.h
src/Scene/ProjectActorFactory.cpp

This PR adds `SwingMapParts` functions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/321)

Library/MapObj: Implement `SwingMapParts`

---

src/Item/CoinCollect.cpp
src/Item/CoinCollect.h
src/Scene/ProjectActorFactory.cpp
src/Util/ShadowUtil.h
src/Util/WaterSurfaceShadow.h

Another one of the big coin classes. This one controls the special coin type of each region.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/323)

Item: Implement CoinCollect

---

lib/al/Library/LiveActor/ActorSensorController.cpp
lib/al/Library/LiveActor/ActorSensorController.h
lib/al/Project/HitSensor/HitSensor.h

This PR is the first one of a series of PRs that implement the `HitSensor` system. This PR implements the `ActorSensorController` class and the unused `ActorSensorControllerList` class. It also updates the header for `HitSensor` which will be updated more in a future `HitSensor` system PR
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/326)

Library/LiveActor: Implement ActorSensorController & ActorSensorControllerList

---

lib/al/Library/LiveActor/HitReactionKeeper.h

A header-only PR: Here, I add `HitReactionInfo` and `HitReactionKeeper`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/329)

Library/LiveActor: Add `HitReactionKeeper`

---

lib/al/Library/Nature/WaterSurfaceFinder.h
src/Util/WaterSurfaceShadow.cpp
src/Util/WaterSurfaceShadow.h

I couldn't believe that I confused a vector with 3 floats in #323 so I decided to fully implement this helper class. I didn't make a mistake this time. Although I'm not confident in the member names.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/331)

Util: Implement WaterSurfaceShadow

---

lib/al/Library/LiveActor/ActorSensorFunction.h
lib/al/Project/HitSensor/HitSensor.h
lib/al/Project/HitSensor/HitSensorDirector.cpp
lib/al/Project/HitSensor/HitSensorDirector.h
lib/al/Project/HitSensor/SensorHitGroup.h
tools/check-format.py

This PR implements `HitSensorDirector`, a class that is responsible for checking for collisions between two `HitSensor`s. I've also added two small fixes to checks in the linter that were causing issues and might need to add one more to allow extra `private:` blocks
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/334)

Project/HitSensor: Implement `HitSensorDirector`

---

lib/al/Library/HitSensor/HitSensorKeeper.cpp
lib/al/Library/HitSensor/HitSensorKeeper.h
lib/al/Project/HitSensor/HitSensor.cpp
lib/al/Project/HitSensor/HitSensor.h

This PR implements `HitSensorKeeper` which is used to store all `HitSensor`s of a `LiveActor`. I made it a `friend class` of `HitSensor` since 5 getters/setters would otherwise need to be added
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/340)

Library/HitSensor: Implement `HitSensorKeeper`

---

src/MapObj/SpaceShuttleChild.cpp
src/MapObj/SpaceShuttleChild.h

The child actor used by an unused actor `SpaceShuttle` (and I don't remember which one it is from this video) https://www.youtube.com/watch?v=CcOn23U9ULY
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/345)

MapObj: Implement `SpaceShuttleChild`

---

src/Area/StainArea.cpp
src/Area/StainArea.h

A 3 function class to kick off the `src/Area` folder
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/357)

Area: Implement `StainArea`

---

lib/al/Library/Scene/SceneStopCtrl.cpp
lib/al/Library/Scene/SceneStopCtrl.h
lib/al/Library/Screen/ScreenCoverCtrl.cpp
lib/al/Library/Screen/ScreenCoverCtrl.h
lib/al/Library/Screen/ScreenFunction.h

Backlog from my develop branch.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/354)

Library: Implement `SceneStopCtrl` and `ScreenCoverCtrl`

---

src/Sequence/GameSequenceInfo.cpp
src/Sequence/GameSequenceInfo.h
src/System/GameDataHolder.h

Backlog from my develop branch.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/355)

Sequence: Implement `GameSequenceInfo`

---

lib/al/Library/Scene/SceneUtil.h
src/Scene/StageScene.h
src/Scene/StageSceneStateGetLifeMaxUpItem.cpp
src/Scene/StageSceneStateGetLifeMaxUpItem.h
src/System/GameDataFunction.h

Backlog from my develop branch. Also completes the `SceneUtil.h` header
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/356)

Scene: Implement `StageSceneStateGetLifeMaxUpItem`

---

lib/al/Library/Controller/InputFunction.cpp
src/Enemy/Popn.cpp
src/Layout/MenuSelectParts.cpp
src/Layout/RaceCountDownLayout.cpp
src/MapObj/DoshiStateWanderBossBattle.cpp
src/Player/HackerStateWingFly.cpp

Listsym reported multiple functions that couldn't be found. Some required inline others needed to be added to the csv.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/360)

all: Fix some listsym issues

---

src/Layout/SimpleLayoutMenu.cpp
src/Layout/SimpleLayoutMenu.h

Backlog from my develop branch.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/353)

Layout: Implement `SimpleLayoutMenu`

---

src/MapObj/SphinxRideMiniGameObjGenerator.cpp
src/MapObj/SphinxRideMiniGameObjGenerator.h

An unused class that has a very descriptive name that doesn't leave a lot of room for interpretation. I think this class must have been used in Moon Kingdom for the tracewalking NPC or maybe for some dialog options by Uncle Amiibo.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/344)

MapObj: Implement `SphinxRideMiniGameObjGenerator`

---

src/MapObj/BarrelStack2D.cpp
src/MapObj/BarrelStack2D.h

Implements `BarrelStack2D`, which gets used by `DonkeyKong2D`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/365)

MapObj: Implement `BarrelStack2D`

---

lib/al/Library/Collision/PartsConnector.h
lib/al/Library/LiveActor/ActorModelFunction.h
lib/al/Library/Nature/NatureUtil.h
src/Item/Coin.cpp
src/Item/Coin.h
src/Item/CoinRotateCalculator.h
src/Scene/ProjectActorFactory.cpp
src/Util/DemoUtil.h
src/Util/ShadowUtil.h

This isn't a coin helper this is the actual coin actor. A huge class with a lot of nerves and a pain to implement.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/352)

Item: Implement `Coin`

---

src/Scene/ProjectActorFactory.cpp

We need a reminder to not forget these ones.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/376)

Scene: Add actors to ProjectActorFactory

---

lib/al/Library/Camera/CameraViewCtrl.cpp
lib/al/Library/Camera/CameraViewCtrl.h

Hope its good
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/384)

Library/Camera: Implement `CameraViewCtrl`

---

lib/al/Library/Camera/CameraSwitchRequestInfo.h
lib/al/Library/Camera/CameraSwitchRequester.cpp
lib/al/Library/Camera/CameraSwitchRequester.h
lib/al/Library/Camera/CameraTicket.h
lib/al/Project/Camera/CameraAngleCtrlInfo.h

:3
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/385)

Library/Camera: Implement `CameraSwitchRequester`

---

lib/al/Library/Camera/CameraArrowCollider.h
lib/al/Library/Camera/CameraOffsetCtrl.h
lib/al/Library/Camera/CameraOffsetCtrlPreset.h
lib/al/Library/Camera/CameraPoser.h
lib/al/Library/Camera/CameraPoserFunction.h
lib/al/Library/Camera/CameraStartInfo.h
lib/al/Library/Play/Camera/CameraVerticalAbsorber.cpp
lib/al/Library/Play/Camera/CameraVerticalAbsorber.h
lib/al/Library/Projection/OrthoProjectionInfo.h

Part of my splitting
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/386)

Library/Camera: Add various headers

---

src/System/PlayerHitPointData.cpp
src/System/PlayerHitPointData.h

Data object for Mario's health.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/387)

System: Implement `PlayerHitPointData`

---

lib/al/Library/MapObj/WobbleMapParts.cpp
lib/al/Library/MapObj/WobbleMapParts.h
src/Scene/ProjectActorFactory.cpp

This PR adds `WobbleMapParts` functions.
This class is a bit complex. Even with the implementation, I'm having trouble finding the correct names for the members.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/349)

Library/MapObj: Implement `WobbleMapParts`

---

src/Player/PlayerActionDiveInWater.cpp
src/Player/PlayerActionDiveInWater.h

Finally, some time to implement something myself again. Starting small: `PlayerActionDiveInWater`, consisting of four functions, determines whether the player can dive into water, and starts the animation if required.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/395)

Player: Implement `PlayerActionDiveInWater`

---

src/Npc/ShineTowerNpc.cpp
src/Npc/ShineTowerNpc.h
src/Util/NpcEventFlowUtil.h

Presumably the globe on the odyssey or related to it.
I'm a little confused with `getRemainingShineCount`, it's really weird that putting it inside of `ShineTowerNpc` makes it mismatch despite looking like a call to a function within it, but I haven't found another way to make it match.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/394)

Util: Implement `ShineTowerNpc`

---

lib/al/Library/Area/AreaObj.h
lib/al/Library/Camera/CameraStopJudge.cpp
lib/al/Library/Camera/CameraStopJudge.h

I have implemented CameraStopJudge.
No other additions where required apart form the .cpp file
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/328)

Camera: Implemented `CameraStopJudge`

---

src/Amiibo/HelpAmiiboInvincibleAttack.cpp
src/Amiibo/HelpAmiiboInvincibleAttack.h

Another simple one.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/402)

Amiibo: Implement HelpAmiiboInvincibleAttack

---

src/Amiibo/HelpAmiiboNavigateCoinCollect.cpp
src/Amiibo/HelpAmiiboNavigateCoinCollect.h
src/ModeBalloon/TimeBalloonHintArrow.h

Very long name for a very short class. It also creates the folder ModeBalloon for the first time.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/405)

Amiibo: Implement HelpAmiiboNavigateCoinCollect

---

lib/al/Library/Camera/CameraPoser.h
lib/al/Library/Camera/CameraPoserFix.cpp
lib/al/Library/Camera/CameraPoserFix.h
lib/al/Library/Camera/CameraPoserFunction.h

matches :D
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/409)

Library/Camera: Implement `CameraPoserFix`

---

src/Player/CollisionShapeInfo.h
src/Util/CollisionShapeFunction.cpp
src/Util/CollisionShapeFunction.h

Simple. Easy. Nothing special.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/404)

Util: Implement `CollisionShapeFunction`

---

lib/al/Library/Event/IEventFlowEventReceiver.h
lib/al/Library/Math/ParabolicPath.h
src/Npc/VolleyballBall.cpp
src/Npc/VolleyballBall.h
src/Npc/VolleyballNpc.h

The ball actor in the volleyball minigame. Interesting note. The full path is defined from the very first hit.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/414)

Npc: Implement VolleyballBall

---

lib/al/Library/Collision/CollisionPartsKeeperUtil.h
lib/al/Library/LiveActor/ActorMovementFunction.h
lib/al/Library/LiveActor/ActorSensorMsgFunction.h
lib/al/Library/Movement/AnimScaleController.cpp
lib/al/Library/Movement/AnimScaleController.h
src/Enemy/Pecho.cpp
src/Enemy/Pecho.h
src/Scene/ProjectActorFactory.cpp

Another enemy request. This time is magmato(pecho) they roll and convert to liquid. Requires https://github.com/open-ead/sead/pull/156 to match and compile
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/373)

Enemy: Implement `Pecho`

---

lib/al/Library/KeyPose/KeyPoseKeeper.cpp
lib/al/Library/KeyPose/KeyPoseKeeper.h
lib/al/Library/KeyPose/KeyPoseKeeperUtil.cpp
lib/al/Library/KeyPose/KeyPoseKeeperUtil.h
lib/al/Library/MapObj/FloaterMapParts.cpp
lib/al/Library/MapObj/KeyMoveMapParts.cpp
lib/al/Library/MapObj/KeyMoveMapPartsGenerator.cpp
lib/al/Library/Obj/KeyMoveFollowTarget.cpp
lib/al/Project/Joint/KeyPose.h
src/Boss/BossForest/BossForestWander.cpp

This PR adds `KeyPoseKeeper` and most of it's utils functions.
I had to split `KeyPoseKeeper` to match `createKeyPoseKeeper`.
The name can be changed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/418)

Library/KeyPose: Implement `KeyPoseKeeper` and `KeyPoseKeeperUtil`

---

src/Item/Coin2DCity.cpp
src/Item/Coin2DCity.h
src/Item/Coin2DCityDirector.h
src/Scene/ProjectActorFactory.cpp

Next one on the list. Some blinking coins. I don't actually remember these in game.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/422)

Item: Implement `Coin2DCity`

---

lib/al/Library/Bgm/BgmBeatCounter.cpp
lib/al/Library/Bgm/BgmBeatCounter.h
lib/al/Library/Bgm/BgmLineFunction.h

I'm going to be honest. I don't understand the logic here at all. Either is all wrong or I'm interpreting everything wrong. But at least everything is matching.
From the class name I asume this class counts the beats if they are above the threshold provided. `isTriggerBeat` returns true if the provided beat interval has been running for at least an specific amount of time. But again this function implementation looks nothing like that.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/423)

Library/Bgm: Implement `BgmBeatCounter`

---

lib/al/Library/Camera/CameraTargetAreaLimitter.h
lib/al/Project/Camera/CameraObjectRequestInfo.h

some small headers, so It wont pause other devs too long
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/426)

al/Camera: Add `CameraTargetAreaLimitter` and `CameraObjectRequestInfo`

---

lib/al/Library/Camera/CameraPoserSceneInfo.cpp
lib/al/Library/Camera/CameraPoserSceneInfo.h
lib/al/Library/Play/Camera/CameraVerticalAbsorber.h

Pre work for my main CameraPoser PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/428)

Library/Camera: Implement `CameraPoserSceneInfo`

---

lib/al/Library/Rail/RailUtil.h
src/MapObj/MoonWorldCaptureParadeLift.cpp
src/MapObj/MoonWorldCaptureParadeLift.h
src/Scene/ProjectActorFactory.cpp

I spun a random number generator up and it picked this class on the `File Listings` page of the function sheet. Pretty fun!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/430)

MapObj: Implement `MoonWorldCaptureParadeLift`

---

src/Boss/GolemClimb/GolemClimbFootPrint.cpp
src/Boss/GolemClimb/GolemClimbFootPrint.h

Is this the smallest actor file in the game? 20 lines. It doesn't even use a nerve.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/436)

Boss/GolemClimb: Implement `GolemClimbFootPrint`

---

src/Item/Coin2D.cpp
src/Item/Coin2D.h

I kind of feel like I did this long ago. But is not on master nor my branches so here it is . The common 2d coin.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/424)

Item: Implement `Coin2D`

---

lib/al/Library/Scene/SceneObjHolder.h
lib/al/Library/Scene/SceneObjUtil.h
lib/al/Library/Stage/StageResourceList.h
src/Amiibo/AmiiboNpcDirector.cpp
src/Amiibo/AmiiboNpcDirector.h
src/Amiibo/HelpAmiiboCoinCollect.cpp
src/Amiibo/HelpAmiiboNavigateCoinCollect.cpp
src/Item/Coin2DCity.cpp
src/Item/CoinCollect.cpp
src/Item/CoinCollect2D.cpp
src/Item/CoinCollectHolder.h
src/Item/CoinCollectWatcher.h
src/Item/CoinRotateCalculator.cpp
src/Layout/KidsModeLayoutAccessor.cpp
src/Layout/KidsModeLayoutAccessor.h
src/MapObj/CoinCollectHintObj.cpp
src/System/GameDataHolder.h
src/System/GameDataHolderAccessor.cpp

This PR refactor `getSceneObj` system to avoid class name duplication.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/451)

Library/Scene: Refactor `SceneObjUtil`

---

lib/al/Library/Camera/CameraInputHolder.cpp
lib/al/Library/Effect/EffectKeeper.h
lib/al/Library/LiveActor/ActorAnimFunction.h
lib/al/Library/LiveActor/ActorModelFunction.h
lib/al/Library/LiveActor/ActorMovementFunction.h
lib/al/Library/LiveActor/ActorSensorUtil.h
src/Npc/Achievement.h
src/System/GameDataHolder.h

Inspired by #452 I decided to search for more instances of this common issue. Because no one wants to run into a mismatch caused by a bad header.
The regex was too complicated to implement on the linter. So I just narrowed the options and picked by hand the ones with issues.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/453)

All: Fix multiple headers

---

lib/al/Library/Play/Layout/TalkMessageVoicePlayer.h
src/Layout/ShopUtil.cpp
src/Layout/ShopUtil.h

Utility functions for shops.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/445)

Layout: Implement `ShopUtil`

---

lib/al/Library/Fluid/JointRippleGenerator.cpp
lib/al/Library/Fluid/JointRippleGenerator.h

Trying to fix doshi init function led me to implement this class to verify for member type errors.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/460)

Library/Fluid: Implement `JointRippleGenerator`

---

lib/al/Library/Layout/LayoutActionFunction.cpp
lib/al/Library/Layout/LayoutActionFunction.h
lib/al/Library/Layout/LayoutActionKeeper.h
lib/al/Library/Layout/LayoutPaneGroup.h

Some random functions that I did last summer. The rest require a `al::LayoutTextPaneAnimator` header that I can't bother making.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/466)

Library/Layout: Implement most of `LayoutActionFunction`

---

lib/al/Library/Area/SwitchAreaDirector.cpp
lib/al/Library/Area/SwitchAreaDirector.h
lib/al/Library/Area/SwitchAreaTargetInfo.h
lib/al/Library/Area/SwitchKeepOnAreaGroup.h
lib/al/Library/Area/SwitchOnAreaGroup.h

This PR:
- add `SwitchAreaDirector` functions.
- fix `SwitchOnAreaGroup` and `SwitchKeepOnAreaGroup` headers.
- add a header for `SwitchAreaTargetInfo`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/472)

Library/Area: Implement `SwitchAreaDirector`

---

src/Player/PlayerJudgeInvalidateInputFall.cpp
src/Player/PlayerJudgeInvalidateInputFall.h

Taking a short break this simple class. Nothing special, everything matched, no issues.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/465)

Player: Implement `PlayerJudgeInvalidateInputFall`

---

lib/al/Library/Area/SwitchAreaDirector.cpp
lib/al/Library/Area/SwitchAreaTargetInfo.cpp
lib/al/Library/Area/SwitchAreaTargetInfo.h

This PR adds `SwitchAreaTargetInfo` functions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/488)

Library/Area: Implement `SwitchAreaTargetInfo`

---

src/Enemy/EnemyCap.cpp

This function was very broken but not anymore.  Just to have an example that this PR https://github.com/open-ead/sead/pull/178 actually fixes stuff I decided to fix this one.
In case is not clear. Requires the sead change to match.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/469)

EnemyCap: Fix updatePose

---

src/System/GameDataHolderWriter.h
src/System/SaveObjInfo.cpp
src/System/SaveObjInfo.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/491)

System: Implement `SaveObjInfo`

---

src/MapObj/ShineTowerBackDoor.cpp
src/MapObj/ShineTowerBackDoor.h
src/Util/PlayerPuppetFunction.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/498)

MapObj: Implement `ShineTowerBackDoor`

---

lib/al/Library/Matrix/MatrixUtil.cpp
lib/al/Library/Matrix/MatrixUtil.h
tools/check-format.py

It was fun while it lasted. Implements a bunch of MatrixUtil operations. I didn't implement the rest because they doesn't match and I'm not willing to put more time and effort into this class for a long while.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/483)

Library/Matrix: Partially implement MatrixUtil

---

lib/al/Library/Collision/CollisionPartsKeeperUtil.h
src/Enemy/EnemyStateSwoon.cpp
src/Enemy/EnemyStateSwoon.h
src/Enemy/Gamane.cpp

Finally some family friendly class with none of the math related stuff. This one seems to handle the swoon animation sequence. It consist on 3 stages start, loop and end. With a few variants on the way like trampled, near water or falling.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/487)

Enemy: Implement EnemyStateSwoon

---

src/Npc/Bird.h
src/Npc/BirdPlayerGlideCtrl.cpp
src/Npc/BirdPlayerGlideCtrl.h
src/Scene/ProjectActorFactory.cpp
src/System/GameDataFile.cpp
src/System/GameDataFile.h
src/System/GameDataFunction.cpp
src/System/GameDataHolder.h
src/Util/ScenePlayerCapFunction.h

Also implemented `GameDataFunction::isGameClear` because it's used in `BirdPlayerGlideCtrl::exeValidOnNose`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/442)

Npc: Implement `BirdPlayerGlideCtrl`

---

lib/al/Project/Thread/InitializeThread.cpp
lib/al/Project/Thread/InitializeThread.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/493)

Project/Thread: Implement `InitializeThread`

---

lib/al/Library/Fluid/FlowMapParts.cpp
lib/al/Library/Fluid/FlowMapParts.h
lib/al/Library/LiveActor/ActorModelFunction.h
lib/al/Project/Fluid/FlowMapCtrl.cpp
lib/al/Project/Fluid/FlowMapCtrl.h
src/Scene/ProjectActorFactory.cpp

I added FlowMapParts as a friend to FlowMapCtrl so I could set its variables. I can do setters instead if you prefer that, or we could make it a struct since its a really small class that only used by two classes in the game.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/508)

Library/Fluid: Implement `FlowMapParts` & `FlowMapCtrl`

---

lib/al/Library/Area/AreaObj.h
lib/al/Library/Area/AreaObjGroup.h
lib/al/Library/Area/SwitchAreaTargetInfo.cpp
lib/al/Library/Area/SwitchAreaTargetInfo.h
lib/al/Library/Area/SwitchKeepOnAreaGroup.cpp
lib/al/Library/Area/SwitchKeepOnAreaGroup.h
lib/al/Project/Camera/CameraAngleVerticalRequester.cpp
src/Amiibo/HelpAmiiboCoinCollect.cpp
src/Enemy/HackerDepthShadowMapCtrl.cpp

This PR adds `SwitchKeepOnAreaGroup` functions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/511)

Library/Area: Implement `SwitchKeepOnAreaGroup`

---

src/MapObj/SaveFlagCheckObj.cpp
src/MapObj/SaveFlagCheckObj.h
src/Scene/ProjectActorFactory.cpp

pr any% wr
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/505)

MapObj: Implement `SaveFlagCheckObj`

---

lib/al/Library/Obj/BreakModel.cpp
lib/al/Library/Yaml/ByamlHeader.cpp

A silent compiler is a happy one.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/527)

Library: Remove warnings from Byaml and BreakModel

---

src/MapObj/HipDropSwitch.h
src/MapObj/RouletteSwitch.cpp
src/MapObj/RouletteSwitch.h
src/Scene/ProjectActorFactory.cpp

I believe these are the switches that stop the platforms in Ruined's rocket subarea.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/532)

MapObj: Implement `RouletteSwitch`

---

lib/al/Library/Resource/Resource.cpp
lib/al/Library/Resource/Resource.h
lib/al/Library/Stage/StageResourceList.cpp

This PR add `Resource` functions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/529)

Library/Resource: Implement `Resource`

---

lib/al/Library/Collision/Collider.h
src/MapObj/MapObjStatePlayerHold.cpp
src/MapObj/MapObjStatePlayerHold.h

A simple class with a bit of math but nothing that we haven't done before. From what I understand it allows to pick up and throw objects.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/539)

MapObj: Implement `MapObjStatePlayerHold`

---

lib/al/Library/Event/EventFlowUtil.h
lib/al/Library/Joint/JointControllerBase.h
lib/al/Library/Joint/JointControllerKeeper.h
lib/al/Library/Joint/JointLocalAxisRotator.h
lib/al/Library/Play/Camera/ActorMatrixCameraTarget.h
src/MapObj/HackFork.cpp
src/MapObj/HackFork.h
src/Player/PlayerHackKeeper.h
src/Scene/GuidePosInfoHolder.h
src/Scene/ProjectActorFactory.cpp
src/Util/Hack.h
src/Util/NpcAnimUtil.h
tools/check-format.py

An insane difficulty class. It has a little bit of everything, huge amount of members, new headers, sead changes, matrix operations, quat operations, vector operations, mismatches and controller input. Overall I was able to match most of the class but I'm blocked by the remaining issues.
Important things to note. The controller input is an average of the last 10 inputs. You have 10 frames to do a swing jump.
I might invest more time in resetCapMtx in the following days to make sure it's at least 90% matching.
Mismatches:
- **HackFork::init** Regswap and missing instructions https://decomp.me/scratch/NeUHJ
- **HackFork::trySwingJump** Wrong loading order https://decomp.me/scratch/VW7ZF
- **HackFork::shoot** https://decomp.me/scratch/8ReuA
- ~~HackFork::control Fixed by …

MapObj: Implement HackFork

---

src/MapObj/VolleyballBase.cpp
src/MapObj/VolleyballBase.h

Fully implemented by @Slycermusic, I only cleaned up the result.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/549)

MapObj: Implement `VolleyballBase`

---

lib/al/Library/Placement/PlacementId.cpp
lib/al/Library/Placement/PlacementId.h
src/System/UniqObjInfo.cpp
src/System/UniqObjInfo.h

Needs open-ead/sead#188.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/535)

System: Implement `UniqObjInfo`

---

lib/al/Library/Camera/CameraTargetBase.h
lib/al/Library/MapObj/SwitchOpenMapParts.cpp
lib/al/Library/MapObj/VisibleSwitchMapParts.cpp
lib/al/Library/Obj/EffectObjFollowCamera.cpp
lib/al/Library/Obj/EffectObjFollowCameraLimit.cpp
lib/al/Library/Rail/RailKeeper.h
src/Amiibo/SearchAmiiboDataTable.h
src/Item/CoinCollectWatcher.h
src/Player/PlayerJudgeSlopeSlide.h
src/Player/PlayerJudgeStartSquat.h
src/Sequence/WorldResourceLoader.h

Used [a script](https://gist.github.com/0f-0b/d5a694cc5767b38599c8b8cf2f81e42b) to find a few classes that are misplaced or inherit from the wrong bases.
[Full output of the script](https://github.com/user-attachments/files/19768983/classes.txt).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/550)

all: Fix class declarations based on RTTI

---

lib/al/Library/Draw/GraphicsSystemInfo.h
lib/al/Library/Layout/LayoutSystem.h
lib/al/Library/LiveActor/LiveActorKit.h
lib/al/Library/Model/ModelOcclusionCullingDirector.h
lib/al/Library/Model/SkyDirector.h
lib/al/Library/Scene/Scene.cpp
lib/al/Library/Scene/Scene.h
lib/al/Project/LiveActor/ActorExecuteFunction.h

The superclass of all "standard" scenes, most importantly `StageScene`. This one does not contain that much logic, a few more headers were needed to implement this one properly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/551)

Library/Scene: Implement `Scene`

---

src/Item/CoinRail.cpp
src/Item/CoinRail.h
src/Scene/ProjectActorFactory.cpp

This one has been on the burner for a while but monster already had a matching implementation so I just cleaned up.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/555)

Item: Implement `CoinRail`

---

lib/al/Library/MapObj/RollingCubeMapParts.cpp
lib/al/Project/Joint/RollingCubePoseKeeper.cpp
lib/al/Project/Joint/RollingCubePoseKeeper.h
lib/al/Project/Joint/RollingCubePoseKeeperUtil.cpp
lib/al/Project/Joint/RollingCubePoseKeeperUtil.h
lib/al/Project/RollingCubePose.h

Implements `RollingCubePoseKeeper` and `RollingCubePoseKeeperUtil` with the exception of calcMtxLandEffect and calcRollingCubeClippingInfo these require sead changes that I will do in a following PR.
Given the way is inlined RollingCubePoseKeeperUtil  doesn't share the same file as the keeper. `RollingCubePose` doesn't have a defined location on the yml list. So it's placed on the root of Project.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/554)

Project/Joint: Implement `RollingCubePoseKeeper`

---

lib/al/Library/Placement/PlacementFunction.cpp
lib/al/Library/Placement/PlacementId.cpp
lib/al/Library/Placement/PlacementId.h
lib/al/Library/Stage/StageSwitchDirector.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/557)

Library/Placement: Complete `PlacementId`

---

lib/al/Project/Joint/KeyPose.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/566)

Project/Joint: Implement `KeyPose`

---

lib/al/Library/Area/AreaShape.cpp
lib/al/Library/Camera/CameraUtil.h
lib/al/Library/Layout/LayoutActionFunction.cpp
lib/al/Library/LiveActor/ActorInitUtil.cpp
lib/al/Library/LiveActor/ActorPoseKeeper.cpp
lib/al/Library/Model/SkyDirector.h
lib/al/Library/Placement/PlacementFunction.cpp
lib/al/Library/Placement/PlacementFunction.h
lib/al/Library/Se/SeKeeper.h
lib/al/Library/Yaml/Writer/ByamlWriterData.cpp
lib/al/Library/Yaml/Writer/ByamlWriterData.h
lib/al/Project/Action/ActionBgmCtrl.h
src/Player/PlayerCollider.h
src/Util/InputInterruptTutorialUtil.h

Since I keep seeing them I made a script that let's me find them easily even if the code isn't in use. This removes extra symbols found in listsym and removes all mismatched tags in the project.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/571)

All: Remove extra symbols and mismatched tags

---

lib/al/Library/Base/StringUtil.h
lib/al/Library/Draw/SubCameraRenderer.h
lib/al/Library/Layout/LayoutActorUtil.h
src/Layout/CounterLifeCtrl.cpp
src/Layout/CounterLifeCtrl.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/562)

Layout: Implement `CounterLifeCtrl`

---

lib/al/Library/Math/MathUtil.h
lib/al/Project/Joint/RollingCubePoseKeeperUtil.cpp
lib/al/Project/RollingCubePose.cpp
lib/al/Project/RollingCubePose.h

It will be easy they said. I didn't expect a 2.1k pure math function. But everything is implemented and matching.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/568)

Project: Implement RollingCubePose

---

lib/al/Library/Collision/Collider.h
lib/al/Library/Joint/JointControllerKeeper.h
lib/al/Library/Joint/JointSpringController.h
lib/al/Library/LiveActor/LiveActorKeeper.h
lib/al/Library/Play/Camera/CameraPoserSubjective.h
src/Player/HackerStateNormalMove.h
src/Player/PlayerPushReceiver.h

Megane is over 1.5k lines long. To help the review process I decided to PR all the headers separately.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/561)

Enemy: Add Megane headers

---

lib/al/Library/Area/TrafficArea.cpp

This PR add `TrafficArea` functions.
Close https://github.com/MonsterDruide1/OdysseyDecompTracker/issues/1559
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/576)

Library/Area: Implement `TrafficArea`

---

lib/al/Library/Area/AreaObj.h
lib/al/Library/Area/AreaObjUtil.cpp
lib/al/Library/Area/AreaObjUtil.h
lib/al/Library/Area/SwitchKeepOnAreaGroup.cpp
lib/al/Project/Camera/CameraAngleVerticalRequester.cpp
src/Amiibo/HelpAmiiboCoinCollect.cpp
src/Enemy/HackerDepthShadowMapCtrl.cpp

This PR add `AreaObjUtil` functions.
Close https://github.com/MonsterDruide1/OdysseyDecompTracker/issues/1555
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/574)

Library/Area: Implement `AreaObjUtil`

---

src/MapObj/AppearSwitchSave.cpp
src/MapObj/AppearSwitchSave.h
src/MapObj/RiseMapParts.h
src/MapObj/RiseMapPartsHolder.h

Pretty sure the arrays are structs, but idk if there's a known struct for it
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/575)

MapObj: Implement `AppearSwitchSave`

---

lib/al/Library/Area/AreaObjUtil.h
lib/al/Library/Area/ValidatorBase.h
lib/al/Library/LiveActor/ActorAreaFunction.cpp
lib/al/Library/LiveActor/ActorAreaFunction.h

Implements most of the functions of this header. The missing functions use a special kind of bitflag that I was unable to even get a close match. The compiler optimizes for bitflags changing the code drastically.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/579)

Library/LiveActor: Partially Implement `ActorAreaFunction`

---

src/Enemy/Megane.cpp
src/Enemy/Megane.h

The definition of insanity is keep trying the same expecting a different result. This PR fully implements megane but the linter might fail due some compromises I had to make.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/581)

Enemy: Implement `Megane`

---

lib/al/Project/ArchiveEntry.cpp
lib/al/Project/ArchiveEntry.h
lib/al/Project/FileEntryBase.cpp
lib/al/Project/FileEntryBase.h

To clarify a little debate on #585  due resource types I decided to implement both classes. These are also required to implement `FileLoader`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/586)

Project: Implement `ArchiveEntry` and `FileEntryBase`

---

lib/al/Library/Rail/RailKeeper.cpp
lib/al/Library/Rail/RailKeeper.h

This PR add `RailKeeper` functions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/592)

Library/Rail: Implement `RailKeeper`

---

lib/al/Library/Camera/CameraRequestParamHolder.cpp
lib/al/Library/Camera/CameraRequestParamHolder.h

I either did something wrong or this class is weird. Either way is fully matching and required by `SceneUtil`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/596)

Library/Camera: Implement `CameraRequestParamHolder`

---

src/Enemy/PackunPoisonBall.cpp
src/Enemy/PackunPoisonBall.h

This PR add `PackunPoisonBall` functions.
I made a header for this in a @Slycermusic's mod so I decided to implement it in the decomp.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/589)

Enemy: Implement `PackunPoisonBall`

---

src/Player/PlayerInput.h
src/Player/PlayerJudgeWallPush.cpp
src/Player/PlayerJudgeWallPush.h
src/Util/PlayerCollisionUtil.h

Another class from my backlog. We should come up with a solution to get those cos/sin constants properly/cleanly when required, not hardcoding them everywhere.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/598)

Player: Implement `PlayerJudgeWallPush`

---

lib/al/Project/File/SoundItemEntry.cpp
lib/al/Project/File/SoundItemEntry.h
lib/al/Project/File/SoundItemHolder.cpp
lib/al/Project/File/SoundItemHolder.h
lib/al/Project/FileEntryBase.h

Really Similar to ArchiveEntry with similar issues like the friend requirement. Just as an extra note FileLoader doesn't require to be a friend class, this one can access the data correctly via the getter. 
I also think the `_bc` member is an item variant or another id but I don't have any info to know.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/599)

Project/File: Implement `SoundItemEntry` and `SoundItemHolder`

---

lib/al/Library/Play/Layout/BalloonMessage.cpp
lib/al/Library/Play/Layout/BalloonMessage.h
lib/al/Library/Play/Layout/TalkMessageVoicePlayer.h

This PR add `BalloonMessage` functions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/600)

Library/Play/Layout: Implement `BalloonMessage`

---

lib/al/Library/Area/AreaInitInfo.h
lib/al/Library/Camera/CameraParamMoveLimit.cpp
lib/al/Library/Camera/CameraPoserActorRailParallel.cpp
lib/al/Library/Camera/CameraPoserFixActor.h
lib/al/Library/Camera/CameraPoserFixLook.h
lib/al/Library/Camera/CameraPoserFixPoint.h
lib/al/Library/Camera/CameraRequestParamHolder.cpp
lib/al/Library/Camera/CameraRequestParamHolder.h
lib/al/Library/Camera/CameraTargetHolder.h
lib/al/Library/Camera/CameraViewCtrlScene.h
lib/al/Project/Camera/CameraAngleSwingInfo.cpp
src/Enemy/Gamane.cpp
src/Enemy/Popn.cpp

Some old additions that I decided to pr now, it is basically a few headers that need to be added for my next pr, CameraUtils. i added a few there.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/604)

Camera: Preparation headers for CameraUtil

---

lib/al/Library/Play/Layout/RollParts.cpp
lib/al/Library/Play/Layout/RollParts.h

This PR add `RollParts` functions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/606)

Library/Play/Layout: Implement `RollParts`

---

lib/al/Library/Audio/System/AudioKeeperFunction.h
lib/al/Library/Camera/CameraDirector.h
lib/al/Library/Camera/CameraFlagCtrl.h
lib/al/Library/Camera/CameraPoseUpdater.h
lib/al/Library/Camera/CameraViewCtrlPause.h
lib/al/Library/Camera/CameraViewCtrlScene.h
lib/al/Library/Controller/PadRumbleDirector.h
lib/al/Library/Draw/GraphicsQualityController.h
lib/al/Library/Draw/GraphicsSystemInfo.h
lib/al/Library/Effect/EffectKeeper.h
lib/al/Library/Effect/EffectSystem.h
lib/al/Library/Layout/LayoutInitInfo.h
lib/al/Library/Layout/LayoutSystem.h
lib/al/Library/Layout/LayoutUtil.h
lib/al/Library/LiveActor/LiveActorKit.h
lib/al/Library/Play/Camera/SimpleCameraPoserFactory.h
lib/al/Library/PostProcessing/PostProcessingFilter.h
lib/al/Library/Scene/Scene.h
lib/al/Library/Scene/SceneUtil.cpp
lib/al/Library/Scene/SceneUtil.h
lib/al/Library/Screen/ScreenCoverCtrl.cpp
lib/al/Library/Screen/ScreenCoverCtrl.h
lib/al/Library/Se/Function/SeDbFunction.h
lib/al/Library/Se/SeDirectorInitInfo.h
lib/al/Library/Stage/StageResourceKeeper.h
lib/al/Library/Stage/StageResourceList.h
lib/al/Project/Scene/SceneInitInfo.h
tools/check-format.py

Huge file with a lot of influence in multiple headers. Only three functions were left unmatched. These are a bit hard to approach to find a solution.
~~initActorInitInfo -  https://decomp.me/scratch/xJO62~~ Fixed by Narr
~~initLayoutInitInfo - https://decomp.me/scratch/xRiTU~~ Fixed by Monster
initPlacementAreaObj - https://decomp.me/scratch/CBhyQ
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/605)

Library/Scene: Implement `SceneUtil`

---

lib/al/Project/File/FileLoader.cpp
lib/al/Project/File/FileLoader.h
lib/al/Project/File/FileLoaderThread.h
lib/al/Project/FileEntryBase.h

This is the final class of this adventure. I had to add a new function that didn't exist before in the csv otherwise is impossible to match.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/612)

Project/File: Implement `FileLoader`

---

src/Player/PlayerCeilingCheck.cpp
src/Player/PlayerCeilingCheck.h
src/Player/PlayerCollisionCheckSphereMove.h

This class is used to check if the player is able to stand up (or is forced into a squat), can hold an item or is forced to drop it and in case of grabbable ceilings, if it is "in reach".
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/607)

Player: Implement `PlayerCeilingCheck`

---

renovate.json

(still WIP, hopefully Renovate outputs more details in PRs than "validation failed")
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/629)

renovate: Add config for updating `OdysseyDecompToolsCache`

---

lib/al/Library/Collision/PartsConnector.h
lib/al/Library/Collision/PartsConnectorUtil.h
lib/al/Library/Collision/PartsMtxConnector.h
lib/al/Library/MapObj/BreakMapPartsBase.cpp
lib/al/Library/MapObj/VisibleSwitchMapParts.cpp
lib/al/Library/Obj/EffectObj.cpp
lib/al/Library/Obj/EffectObjCameraEmit.cpp
lib/al/Library/Obj/EffectObjInterval.cpp
src/Enemy/PackunTrace.cpp
src/Item/Coin.cpp
src/Item/Coin2D.cpp
src/Item/CoinChameleon.cpp
src/Item/CoinCollect.cpp
src/Item/CoinCollect2D.cpp
src/Item/CoinCollectEmpty.cpp
src/Item/CoinCollectEmpty2D.cpp
src/Item/CoinStateAppearRotate.cpp
src/MapObj/CapSwitch.cpp
src/MapObj/HackFork.cpp
src/MapObj/ShineTowerBackDoor.cpp
src/MapObj/TrampleSwitch.cpp
src/MapObj/TrampleSwitchTimer.cpp
src/MapObj/WeightSwitch.cpp
src/Player/PlayerJudgeWallCatchInputDir.cpp
src/Player/PlayerJudgeWallCatchInputDir.h
src/Util/ObjUtil.h
src/Util/PlayerCollisionUtil.h

One of the more complicated judges, but still overall a comparably easy class.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/587)

Player: Implement `PlayerJudgeWallCatchInputDir`

---

lib/al/Library/Area/AreaObj.h
lib/al/Library/Clipping/ClippingActorInfo.h
lib/al/Library/Clipping/ViewIdHolder.h
lib/al/Library/Play/Area/ViewCtrlArea.h
lib/al/Project/Clipping/ViewInfoCtrl.cpp
lib/al/Project/Clipping/ViewInfoCtrl.h
tools/check-format.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/565)

Project/Clipping: Implemented `ViewInfoCtrl`

---

src/MapObj/TreasureBoxKey.cpp
src/MapObj/TreasureBoxKey.h
src/MapObj/TreasureBoxKeyOpener.h
src/Scene/ProjectActorFactory.cpp

Pretty sure these are the keys strewn about some kingdoms, sometimes as part of a challenge.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/642)

MapObj: Implement `TreasureBoxKey`

---

src/MapObj/AppearSwitchTimer.cpp
src/MapObj/AppearSwitchTimer.h
src/MapObj/RouteGuideDirector.h

I assume this is part of what handles timer challenges.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/640)

MapObj: Implement `AppearSwitchTimer`

---

.clang-format
tools/check-format.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/663)

lint: Set `QualifierAlignment`

---

src/Enemy/Kuribo2D.cpp
src/Enemy/Kuribo2D.h
src/Scene/ProjectActorFactory.cpp
tools/check-format.py

The Goomba enemy found in 8-bit segments.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/664)

Enemy: Implement `Kuribo2D`

---

src/Player/PlayerBindableSensorList.cpp
src/Player/PlayerBindableSensorList.h
tools/check-format.py

Matching implementation of PlayerBindableSensorList.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/181)

Player: Implement PlayerBindableSensorList

---

lib/al/Library/Resource/ActorResource.h
lib/al/Library/Resource/Resource.cpp
lib/al/Library/Resource/Resource.h
lib/al/Library/Resource/ResourceFunction.cpp
lib/al/Library/Resource/ResourceFunction.h
lib/al/Library/Stage/StageResourceList.cpp
lib/al/Project/Resource/ResourceSystem.h
src/Sequence/WorldResourceLoader.cpp

This class was delayed but arrived at the end. Fully implements ResourceFunction.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/685)

Library/Resource: Implement `ResourceFunction`

---

CMakeLists.txt
tools/build.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/696)

build: Use `CONFIGURE_DEPENDS`

---

lib/al/Library/Clipping/ClippingActorHolder.h
lib/al/Library/Clipping/ClippingActorInfo.cpp
lib/al/Library/Clipping/ClippingActorInfo.h
lib/al/Library/Clipping/ClippingActorInfoList.cpp
lib/al/Library/Clipping/ClippingActorInfoList.h
lib/al/Library/Clipping/ClippingGroupHolder.cpp
lib/al/Library/Clipping/ClippingGroupHolder.h
lib/al/Library/LiveActor/ActorInitInfo.cpp
lib/al/Library/LiveActor/ActorInitInfo.h
lib/al/Project/Clipping/ClippingDirector.cpp
lib/al/Project/Clipping/ViewInfoCtrl.cpp
lib/al/Project/Clipping/ViewInfoCtrl.h

Fun class to Implement. I've never dealt with Vectors, BoundBoxes or Matrices. The next Class that I'll look at is `ClippingJudge` That way we can learn about what some of the members do.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/687)

Library/Clipping: Implemented `ClippingActorInfo`

---

.github/scripts/decomp-dev.py
.github/workflows/decomp-dev.yml

Contains changes based on the comments of @encounter on the initial PR. Thanks for reading and improving our config/data!
(would be great if you could review/approve here if you're happy with how I introduced changes based on your suggestions!)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/700)

workflow: Improve data sent to `decomp.dev`

---

lib/al/Project/Effect/EffectLight.cpp
lib/al/Project/Effect/EffectLight.h

Probably the easiest function in the whole decomp, but still my first! 🎉🎉🎉
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/689)

Project/Effect: Implement `EffectLight`

---

lib/al/Library/Area/TrafficArea.cpp
lib/al/Library/Area/TrafficArea.h
lib/al/Library/Area/TrafficAreaDirector.cpp
lib/al/Library/Area/TrafficAreaDirector.h

This PR add `TrafficAreaDirector` functions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/710)

Library/Area: Implement `TrafficAreaDirector`

---

lib/al/Library/Movement/FlashingTimer.cpp
lib/al/Library/Movement/FlashingTimer.h

This PR add `FlashingTimer` functions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/712)

Library/Movement: Implement `FlashingTimer`

---

lib/al/Library/Collision/CollisionPartsKeeperUtil.h
lib/al/Library/Collision/CollisionPartsTriangle.h
lib/al/Library/Collision/KCollisionServer.h
lib/al/Library/Collision/PartsConnectorUtil.cpp
lib/al/Library/Collision/PartsConnectorUtil.h
lib/al/Library/Collision/SensorConnector.h
lib/al/Library/Screen/ScreenPointTarget.h
lib/al/Project/HitSensor/HitSensor.h
tools/check-format.py

Something spicy as a warmup after the long break. Fully implements PartsConnectorUtil.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/722)

Library/Collision: Implement `PartsConnectorUtil`

---

lib/al/Library/Model/ModelDrawBufferUpdater.h
lib/al/Project/LiveActor/ActorExecuteFunction.cpp
lib/al/Project/LiveActor/ActorExecuteFunction.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/732)

Project/LiveActor: Implement `ActorExecuteFunction`
