- lib/al/byaml/ByamlIter.h
* Fixes the function names of all functions that are related to the Int32 format
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/5)
> al/byaml/ByamlIter.h: Fix Int32 names

- lib/al/player/PlayerActorBase.h
I think these are in the wrong position.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/7)
> `al/player`: Correct `getPortNo()` and `getViewMtx()` positions in PlayerActorBase

- lib/al/player/PlayerHolder.h
- lib/al/util/OtherUtil.h
- lib/al/util/PlayerUtil.h
- src/al/player/CMakeLists.txt
- src/al/player/PlayerHolder.cpp
- src/al/util/CMakeLists.txt
- src/al/util/PlayerUtil.cpp
Some notes:
* I couldn't find a `sead` data structure which matches the ordering of the class members in `PlayerHolder` (pointer, size, count).
* ~~I tried implementing `al::getAlivePlayerNum()` with a for loop, but the ordering of two `MOV W##, WZR` instructions would never be right. If I did it with a do-while (which I did in this PR), the ordering matches.~~
* ~~`al::getPlayerPos()` is odd. The game's function uses two `BL`s in a row, but no matter what I do, I always get `BL`, `LDP`, and then `B`. If I remove the return statement, the function would then contain the two `BL`s, but the epilogue would no longer be correct.~~
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/monsterdruide1 …
> `al`: Implement `PlayerHolder` and some utility functions

- .gitignore
Changes `/cmake-build-debug` to `/cmake-build-*` as using a toolchain without changing the build folder will cause the new folder to not be caught by the `.gitignore`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/13)
> `.gitignore`: Fix build folder for non-default CLion toolchains

- .github/workflows/progress.yml
- README.md
- tools/setup.py
Adding a GitHub workflow that only triggers on `master` (and currently this branch for testing), that publishes the progress to a simple `php` script.
PHP:
```php
<?php
$myfile = fopen("progress.json", "w") or die("Unable to open file!");
$pw = $_GET["pw"];
if (strcmp($pw, "[...]") !== 0) {
die("Wrong password!");
}
$matching = $_GET["matching"];
$minor = $_GET["minor"];
$major = $_GET["major"];
$txt = <<<JSON
{
"matching": $matching,
"non_matching_minor": $minor,
"non_matching_major": $major
}
JSON;
fwrite($myfile, $txt);
fclose($myfile);
echo "OK";
?>
```
Publishing the [progress.json](https://monsterdruide.one/OdysseyDecomp/progress.json), which can then be used to render a shield.io-Badge.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
> Add workflow for progress

- .github/scripts/copy-headers.sh
- .github/scripts/push-headers.sh
- .github/workflows/clean-headers.yml
- .github/workflows/copy-headers.yml
This PR adds another workflow, which will be responsible for automatically pushing to the [OdysseyHeaders](https://github.com/MonsterDruide1/OdysseyHeaders) repo.
It will push `master` to `master`, branches on the main repo to their respective name, and PRs to `pr-#` (`#`=PR-number), and automatically clean up deleted branches/closed PRs.
=> this PR will end up on `headers-repo` and `pr-21`.
Some testing on a separate repo has shown that files that are not referenced by the git history will not be cloned with the repository, so after deleting their respective branches, PR/branch files will not take up any more space on the headers repo in the long term.
Please note that this workflow will always only do a single commit on top of the `master` branch, squashing all changes (if multiple …
> Add OdysseyHeaders publishing workflow

- lib/al/include/Library/Audio/AudioDirector.h
- lib/al/include/Library/Audio/IAudioSystemPause.h
- lib/al/include/Library/Camera/SnapShotCameraCtrl.h
- lib/al/include/Library/LiveActor/ActorPoseKeeper.h
- lib/al/include/Library/LiveActor/LiveActor.h
- lib/al/include/Library/LiveActor/SubActorKeeper.h
- lib/al/include/Library/Message/MessageSystem.h
- lib/al/include/Library/Nerve/NerveAction.h
- lib/al/include/Library/Nerve/NerveExecutor.h
- lib/al/include/Library/Nerve/NerveStateCtrl.h
- lib/al/include/Library/Nerve/NerveUtil.h
- lib/al/include/Library/Placement/PlacementFunction.h
- lib/al/include/Library/Resource/Resource.h
- lib/al/include/Library/System/SystemKit.h
- lib/al/include/Project/Light/ActorPrepassLightKeeper.h
- lib/al/include/Project/Play/Graphics/IUseGridMesh.h
- src/Player/HackerJudge.h
- src/Player/PlayerActorHakoniwa.h
- src/Player/PlayerTrigger.h
- src/System/Application.h
- src/System/ProjectInterface.h
- tools/check-format.py
As a preparation for more precise linter actions regarding visibility and naming of specific parts in classes, this PR will eliminate all lines outside of visibility blocks in classes, with a few exceptions:
- Empty lines - for obvious reasons
- `};` is a specifically defined as exception here, due to how this method is implemented (closing braces of the class), only relevant when a class does not have any content yet
- `SEAD_SINGLETON_DISPOSER` and `SEAD_RTTI_BASE` as well as `SEAD_RTTI_OVERRIDE`, as those should be given at the very top of the class and bring their own visibility modifiers at the start of the macro
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/Odyssey …
> lint: Only allow specific lines outside of visibility block in classes

- lib/al/include/Library/Camera/CameraDirector.h
- lib/al/include/Library/LiveActor/LiveActorGroup.h
- lib/al/include/Library/Scene/GameDataHolderBase.h
- lib/al/include/Library/Screen/ScreenFunction.h
- src/Layout/StageSceneLayout.h
- src/MapObj/WorldMapEarth.h
- src/Player/PlayerConst.h
- src/Player/PlayerModelChangerHakoniwa.h
- tools/check-format.py
This introduces another level of linter-magicness, geared towards detecting superclass specifications (`:`) that are missing a `public` statement. Currently, we have no instances of objects needing protected or private superclasses, so generally enforcing this seems like a good idea - and reduces the number of possible human-made errors along the way.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/31)
> lint: All superclasses must be `public`

- lib/al/src/Library/Yaml/Writer/ByamlWriterStringTable.cpp
- src/Player/PlayerOxygen.cpp
REGRESSION: `sead::DebugFontMgr[...]` destructors are mismatching now, due to https://github.com/open-ead/sead/commit/0f38debe0293670bfdbbd85d82fd4d9fce21c858. We're working on a fix.
PlayerOxygen: Due to the changed implementation in https://github.com/open-ead/sead/commit/33bd7f53c95d74113e22c4801f76fe223cc8ae6a, the function used was changed.
ByamlWriterStringTable: Fixed manually having to set the list in https://github.com/open-ead/sead/commit/8cdf6eb1ee80575457739616d27c61309c55eb8b
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/40)
> Update submodules: NintendoSDK, sead, agl

- lib/al/include/Library/Collision/KCollisionServer.h
- lib/al/include/Library/Math/MathUtil.h
- lib/al/src/Library/Collision/KCollisionServer.cpp
Adding two new classes here: `SphereInterpolator` and `SpherePoseInterpolator`. There's not much to say about it otherwise, I didn't manage to match one of the functions though, mainly due to the compiler picking the wrong assembly command for `fmin`: `fminnm`. I'm not sure what the difference is or why that one is used here, but if anyone has an idea or can improve it, that would be appreciated!
Here is a decomp.me of it: https://decomp.me/scratch/BfAs2
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/37)
> Library/Collision: Implement Sphere[Pose]Interpolator

- lib/al/include/Library/Debug/Host.h
- lib/al/src/Library/Debug/Host.cpp
This PR adds `Host` header and an implementation for almost every functions except `expandEnvironmentString`, `makeTmpExpandEnvironmentString` and a function that has no debug symbols.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/44)
> Host functions

- lib/al/include/Library/Area/AreaShape.h
- lib/al/include/Library/Math/MathUtil.h
- lib/al/src/Library/Area/AreaShapeOval.cpp
Cleaning up some of the branches around this repo, I found this: Seems like I worked on `AreaShapeOval` a while ago, didn't get one of the functions to match and stopped. Now, with this additional function matched (required flipping the `if` statement to _not_ using early returns), I'm happy to merge this in as well.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/43)
> `al/Library/Area`: Finish `AreaShapeOval`

- src/Player/PlayerJudgePreInputJump.cpp
- src/Player/PlayerJudgePreInputJump.h
This `IJudge` is responsible to checking whether a jump should be started. This also explains: Jump-Inputs can be buffered for 5 frames, for example before touching the ground, before the counter "runs out".
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/46)
> Player: Implement PlayerJudgePreInputJump

- src/Player/PlayerJumpMessageRequest.cpp
- src/Player/PlayerJumpMessageRequest.h
This class/struct contains data used to start different types of jumps. A standard jump (standing still, just press A) has type `0`, I didn't try to research other types yet, as they are magic numbers inlined across the whole binary.
I chose to create this as `struct`, as all usages (except `clear()`) are accessing class members directly. Using `get/set` for *all* members sounds wrong, but I'm open to discuss about this if there are other opinions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/47)
> Player: Implement PlayerJumpMessageRequest

- src/Player/IPlayerModelChanger.h
- src/Player/PlayerJudgeStartHipDrop.cpp
- src/Player/PlayerJudgeStartHipDrop.h
- src/Player/PlayerModelChangerHakoniwa.h
- src/Util/PlayerCollisionUtil.h
Doing a `HipDrop` requires you to be not in 2D-mode, press the appropriate button and be at least 40 units above the ground (customizable by `PlayerConst`).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/48)
> Player: Implement PlayerJudgeStartHipDrop

- lib/al/include/Library/Math/MathUtil.h
- src/Player/PlayerCounterForceRun.cpp
- src/Player/PlayerCounterForceRun.h
Simple little class that is just used for storing the current `ForceRun` state (for example rocket flowers, and ... I think that's all), consisting of the duration and speed. If the `mCounter` hits zero, `mSpeed` is ignored, but stay at its old value.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/52)
> Player: Implement PlayerCounterForceRun

- src/Player/PlayerContinuousJump.cpp
- src/Player/PlayerContinuousJump.h
Simple class that is responsible for storing the last jump, which allows for checking whether a double/triple jump is still going in the same direction. If the current nerve is not `Wait` or `Run`, the state will be cleared immediately: For example, it's not possible to double-jump out of a LongJump.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/53)
> Player: Implement PlayerContinuousJump

- src/Player/PlayerContinuousLongJump.cpp
- src/Player/PlayerContinuousLongJump.h
Seems like there is also a counter for the number of continuous long jumps in the game, which helps in selecting a different animation each time - resulting in a total of 8 possible, selectable values.
However, the `PlayerConst` limits this to a maximum of 3 values by default, resulting in the commonly-known animations. By overriding this, we can view some more animations that have not been used in the final game.
Looking at `PlayerAnimation.szs`, we can see `JumpBroad`, `JumpBroad2`, ..., `JumpBroad9` are existing animations. Which means that even when overriding the PlayerConst limit, there is still one animation left in the game files that cannot be viewed in-game *at all* without `exefs` mods.
To summarize again: Nintendo limited us to see 3/9 animations by `PlayerConst`, and 8/9 by …
> Player: Implement PlayerContinuousLongJump

- src/Player/PlayerCounterQuickTurnJump.cpp
- src/Player/PlayerCounterQuickTurnJump.h
- src/Player/PlayerTrigger.h
Another simple class, responsible for detecting `QuickTurn`s and counting down from (default) `20`, allowing to initiate a `QuickTurnJump` in that window, and disallowing it again afterwards.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/62)
> Player: Implement PlayerCounterQuickTurnJump

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- README.md
Exactly what it says in the title. Also, I've added a bit of documentation about how to set up that one, and for installing the dependencies "natively" on Ubuntu 24.04, which has removed the `libncurses5` and `libtinfo5` packages, which will then need to be installed manually from a  `deb`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/63)
> dev: Add Devcontainer setup for VS-Code

- src/Player/PlayerJudgeSpeedCheckFall.cpp
- src/Player/PlayerJudgeSpeedCheckFall.h
- src/Util/PlayerCollisionUtil.h
This class seems to be responsible for managing Coyote-Time when the player runs off an edge, or when the ground is removed beneath the player. This can be confirmed with creating a little mod that will just override the `judge()` with `return false;`, resulting in a behaviour like this:
https://twitter.com/MDruide1/status/1796858571168035140
With this in mind and looking at the code again, we can deduce that the player has either 4 or 5 frames (depending on execution order) before switching to the `Fall` nerve/state.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/51)
> Player: Implement PlayerJudgeSpeedCheckFall

- src/Player/PlayerCounterAfterCapCatch.cpp
- src/Player/PlayerCounterAfterCapCatch.h
- src/Player/PlayerTrigger.h
This `Counter` counts the number of frames since some `AttackSensorTrigger` has triggered. Based on the context, I would believe that this is the Cap "attacking" the player, but I don't feel like the amount of information available here is enough to confidently name the `enum` entry.
After the `AttackSensor` has been triggered, the `CapCatch` action can be executed for (default) `10` frames.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/75)
> Player: Implement PlayerCounterAfterCapCatch

- src/Player/PlayerJudgeForceSlopeSlide.cpp
- src/Player/PlayerJudgeForceSlopeSlide.h
- src/Util/PlayerCollisionUtil.h
- src/Util/PlayerUtil.h
Similar to the `ForceRoll` judge, this one checks for the floor collision code - but also requires the player to *not* be in a hack at the same time. This one is also a bit more optimized towards performance, caching the result of the floor collision in `update`, and only reading the cached value in `judge`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/85)
> Player: Implement PlayerJudgeForceSlopeSlide

- src/Player/PlayerCounterAfterUpperPunch.cpp
- src/Player/PlayerCounterAfterUpperPunch.h
Another counter, that will apparently just continuously count up after `UpperPunchHit` is triggered. I currently have no idea what this is even used for... only thing that would come to my mind is the hat in Bowser's, but ... why would that exist on `PlayerActorHakoniwa` in all stages?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/80)
> Player: Implement PlayerCounterAfterUpperPunch

- src/Player/PlayerCarryKeeper.h
- src/Player/PlayerInput.h
- src/Player/PlayerJudgeStartSquat.cpp
- src/Player/PlayerJudgeStartSquat.h
Another simple judge. Apparently, to initiate a `Squat`, you have to fulfill the following criteria:
1. Do not carry anything
2. Hold the `Squat` button
3. Not in a forced run, for example a rocket flower
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/88)
> Player: Implement PlayerJudgeStartSquat

- lib/al/Library/Base/Macros.h
- lib/al/Library/Nerve/NerveSetupUtil.h
- lib/al/Library/Obj/AllDeadWatcher.h
- lib/al/Library/Obj/BreakModel.cpp
- lib/al/Library/Play/Camera/CameraVerticalAbsorber.cpp
- src/Amiibo/ItemAmiiboKoopa.cpp
- src/Boss/Mofumofu/MofumofuWarpHole.cpp
- src/Layout/BootLayout.cpp
- src/Layout/ButtonMiiverse.cpp
- src/MapObj/AnagramAlphabet.cpp
- src/MapObj/AnagramAlphabetCharacter.cpp
- src/MapObj/FireDrum2D.cpp
- src/Player/Player.cpp
- src/System/GameSystem.cpp
Utility things required for #90. Here, we noticed that macros for `NerveAction`s are required as well, but also that the structs for those include another object used to collect the nerves into a struct that can be searched to find actions by name. This object is placed at the end of the struct, but initialized first, which means that the other objects are not initialized at declaration, but at some later point within the dynamic initialization phase. To re-create this behaviour, these nerves are not stored as their usual type, as that would at least zero-initialize them before the helper struct, instead we just store a `StorageFor` and manually call their creation method during the constructor.
As this setup requires a major overhead with creating the struct and its constructor …
> Library/Nerve: New NerveSetupUtil-macros

- lib/al/Library/Math/MathAngleUtil.h
- lib/al/Library/Math/MathLengthUtil.h
- src/Player/PlayerActionVelocityControl.cpp
- src/Player/PlayerActionVelocityControl.h
- src/Util/PlayerCollisionUtil.h
This class is used as a helper for various calculations within specific functions of `PlayerStateRolling` and `PlayerStateSquat`. It splits the velocity of an actor into its three relative components (up, front, side), and can apply calculations to each one independently, before combining them back together into a single, new movement vector.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/92)
> Player: Implement PlayerActionVelocityControl

- src/Player/PlayerJudgeStartRolling.cpp
- src/Player/PlayerJudgeStartRolling.h
Another quick judge. This one checks a bunch of pre-conditions for switching to the `Rolling` state from various previous states. The base checks are always:
1. Do not carry anything
2. Not currently 2D
3. Player is on ground
4. Ground does not have `ForceSlide` code
Finally, for triggering a roll, each respective `PlayerInput` function has to return true, for example `isTriggerRollingCancelHipDrop` to roll from a ground pound.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/98)
> Player: Implement PlayerJudgeStartRolling

- src/Player/PlayerInput.h
- src/Player/PlayerJudgeStartGroundSpin.cpp
- src/Player/PlayerJudgeStartGroundSpin.h
Simple judge to determine whether the Player should start spinning. To `return true`, the following two conditions have to be fulfilled:
1. Input a spin
2. Player is on the ground
... and that's it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/99)
> Player: Implement PlayerJudgeStartGroundSpin

- src/Player/PlayerJudgeForceLand.cpp
- src/Player/PlayerJudgeForceLand.h
- src/Player/PlayerTrigger.h
Another one! To trigger this judge, either the `PlayerJudgeLongFall` judge passed in the constructor has to return `true`, or the `PlayerTrigger` has to hold the value `11` in its `ActionTrigger`. As the purpose of this value is currently unknown, it only contains a placeholder name in this PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/101)
> Player: Implement PlayerJudgeForceLand

- src/Player/PlayerJudgeSandSink.cpp
- src/Player/PlayerJudgeSandSink.h
- src/Player/PlayerSandSinkAffect.h
- src/Util/PlayerCollisionUtil.h
Another judge? How many of these exist overall?!
... way more than we have done here already.
Alright, next-up: PlayerJudgeSandSink. Determines whether the player should be affected by sinking sand. This is true if the player is already affected by `SandSinkAffect`, or the following two conditions are true:
1. Player is on ground
2. Touched ground collision triangle has collision code `SandSink`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/100)
> Player: Implement PlayerJudgeSandSink

- lib/al/Library/Base/StringUtil.h
- lib/al/Library/Layout/LayoutActor.cpp
- lib/al/Library/LiveActor/LiveActorGroup.cpp
- src/MapObj/AnagramAlphabetCharacter.cpp
- src/Sequence/HakoniwaSequence.h
- tools/check-format.py
Fixes #66 by searching for `this->`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/102)
> Custom linter: Remove `this->` prefix

- lib/al/Library/Controller/SpinInputAnalyzer.cpp
- lib/al/Library/Controller/SpinInputAnalyzer.h
With `sead` being updated in https://github.com/open-ead/sead/pull/139 and https://github.com/open-ead/sead/pull/140, this PR contains fully matching code. The `SpinInputAnalyzer` tracks the stick input across up to 128 frames, and if it follows a spinning pattern with large enough radius, some output variables are set to allow other parts of the game to initiate a spinning action. Of those 128 available frames, only 70 are used for the calculation though, with at least 30 being required to detect an action.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/107)
> Library/Controller: Implement SpinInputAnalyzer

- lib/al/Library/Collision/CollisionParts.h
- src/Player/PlayerCounterForceRun.h
- src/Player/PlayerExternalVelocity.h
- src/Player/PlayerInput.h
- src/Player/PlayerJudgeStartSquat.cpp
- src/Player/PlayerJudgeWallCatch.cpp
- src/Player/PlayerJudgeWallCatch.h
- src/Player/PlayerTrigger.h
- src/Util/ObjUtil.h
- src/Util/PlayerCollisionUtil.h
The first Judge with a bit more logic to it! To grab onto a wall (start wall slide), the following criteria have to be true:
1. Do not carry anything
2. Not in 2D-section
3. Not forced to run (RocketFlower)
4. No external force applied to Mario (for example moving ground, but might be more?)
5. Currently colliding with a wall
6. Currently not colliding with the ground
7. The wall does not have any `NoWallGrab` code (`NoAction, NoWallGrab, ReflectStickNoWallGrab, OnlyWallHitDown, GrabCeil, Pole, Needle, DamageFire`)
8. If currently in `PlayerTrigger::Action_val30` (as far as I can tell enabled when doing a backflip and sideflip), have the stick pressed more than 41% (`length^2 > 0.64`)
9. Finally, succeed in finding a `WallCatchPos`
- - -
This change is [<img …
> Player: Implement PlayerJudgeWallCatch

- src/Layout/MapTerrainLayout.cpp
- src/Layout/MapTerrainLayout.h
- src/System/MapDataHolder.h
This small class contains a single pane of world's map texture. Used in `MapLayout`.
Requires `System/MapDataHolder.h`, along with a `MapData` struct for the loaded data.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/112)
> Layout: Implement `MapTerrainLayout`

- src/Player/PlayerCapActionHistory.cpp
- src/Player/PlayerCapActionHistory.h
- src/Util/PlayerCollisionUtil.h
Another small helper class that keeps track of some statistics about the cap, for example whether the player has already cap-jumped once and the current `HeightLimit` (not sure where this is used). It also keeps track of its own `PlayerCounterAfterCapCatch`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/114)
> Player: Implement PlayerCapActionHistory

- src/Amiibo/SearchAmiiboDataTable.cpp
- src/Amiibo/SearchAmiiboDataTable.h
This class is created and stored in `GameDataFile`, and gets used in `AmiiboNpcDirector` and some `AmiiboFunction` functions. I believe it's used for the amiibo NPC that provides hints to moons.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/115)
> Amiibo: Implement `SearchAmiiboDataTable`

- src/Player/PlayerExternalVelocity.h
- src/Player/PlayerJudgeGrabCeil.cpp
- src/Player/PlayerJudgeGrabCeil.h
- src/Util/ObjUtil.h
- src/Util/PlayerCollisionUtil.h
Another judge with a bit more logic to it. To grab onto a `Ceil`, the following basic conditions have to be fulfilled:
1. Do not carry anything
2. Not in 2D-Mode
3. No external force applied
4. Must be touching any surface with `GrabCeil` collision code (floor, wall or ceiling are all fine)
When those checks are okay and the surface is either `Ground` or `Wall`, there has to be either a `SnapForce` on the player, his velocity must be zero or he must be moving away from the surface with the mentioned collision code.
Finally, some code is invoked to calculate a position to grab onto. This might still fail, so this is another option to have the judge return `false`.
Here is a list of all objects across the entire game that have the `GrabCeil` code:
```
CityWorldHomeSignal000Attribute.byml …
```
> Player: Implement PlayerJudgeGrabCeil

- src/Player/PlayerJudgeDirectRolling.cpp
- src/Player/PlayerJudgeDirectRolling.h
Another mostly-simple judge, this one determines whether the player can go from a dive instantly into a roll (without standing/crouching first). For it to return true, the following conditions have to be fulfilled:
1. Do not be forced to run (rocket flower)
2. Do not carry anything
3. Player must be touching the ground
4. Not in a 2D-area
5. `Squat` must be held down
6. The horizontal speed of the player must be larger than `DashJudgeSpeed` (default: `14.5`)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/124)
> Player: Implement PlayerJudgeDirectRolling

- src/Player/PlayerJudgeAirForceCount.cpp
- src/Player/PlayerJudgeAirForceCount.h
Another simple judge, this one counts the frames for which the player has been in the air and affected by an `ExternalVelocity/Force`. It triggers once the counter hits 40. The counter is increased when the player is in the air and an external velocity/force exists, otherwise immediately reset to zero. Once this judge returns `true`, Mario is forced into the `Fall` state.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/126)
> Player: Implement `PlayerJudgeAirForceCount`

- lib/al/Library/LiveActor/LiveActor.cpp
- lib/al/Library/LiveActor/LiveActor.h
Most of the code in `LiveActor.cpp` and `LiveActor.h` was added 3 years ago before the reformatting. A lot of new formatting guidelines have popped up recently that this file needed. Most notably, the `memset` call in `LiveActor::LiveActor` has been removed and members are now properly initialized with `nullptr`s.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/131)
> LiveActor: Adjust `LiveActor` formatting to better match the rest of the repository

- src/Scene/ProjectActorFactory.cpp
Simple change to add the `createActorFunction` for `al::FallMapParts` added in #130.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/132)
> Scene: Add `al::FallMapParts` to the actor factory

- lib/al/Library/Base/StringUtil.h
This PR adds in `al::WStringTmp` as well as a default constructor for `al::StringTmp`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/137)
> Library/Base: Implement `WStringTmp`

- lib/al/Library/Collision/KCollisionServer.h
I broke the CI by merging a too-old-PR without rebasing first, which means it only conformed old formatting standards, not the newly introduced ones. This should get the CI back to green again.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/142)
> Library/Collision: Format `KCollisionServer`

- .envrc
- .gitignore
- README.md
- flake.lock
- flake.nix
To support an easier setup for Nix-based systems, we should distribute a `flake.nix` with the right dependencies. The setup is done with `direnv allow` then. However, as non-Nix-systems do not know the command `use flake` and will throw an error when direnv is attempted to be used, it is guarded behind a `USE_NIX` variable. This can be set in `.envrc.private`, which is `.gitignore`d and cannot be added as "template" here.
The "Setup"-section of `README` has been adjusted accordingly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/140)
> dev: Add `flake.nix`-devshell and `direnv` setup

- tools/build.py
When the build fails, it should show that it failed, not silently ignore it.
Fixes #61
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/141)
> tools/build: Non-zero return code on build failure

- lib/al/Library/Camera/CameraTicket.cpp
- lib/al/Library/Camera/CameraTicket.h
Next! `CameraTicket` holds the associated `CameraPoser`, (for example `CameraPoserFix`) in pre-configured form, its ticket (from the previous PR) and a certain priority, depending on the type of camera it is used for.
The enum `Priority` holds the currently known values I could gather from a quick search. The type of `setPriority` is `s32`/`int` though, so it can't accept the enum as type. To avoid casting at all usages, this is an `enum` instead of `enum class`. Regarding the entrance priority, I only found `alCameraPoserFunction::isPrePriorityEntranceAll(al::CameraStartInfo const&)`, which checks for *both* values - so this can be adjusted later when other, proper values are found.
- - - …
> Library/Camera: Implement `CameraTicket`

- src/MapObj/CitySignal.cpp
- src/MapObj/CitySignal.h
- src/Scene/ProjectActorFactory.cpp
- src/System/GameDataFunction.h
Today, I felt like doing something useful and implementing *something*. Scrolling around the list of functions randomly resulted in me picking this. Great!
Just as a short note beforehand - `WaitBlue` means `Green`. The other namings are straight-foward.
A bit of investigation later, it seems like the signal is supposed to do more than it actually ends up doing in the game.
https://twitter.com/MDruide1/status/1828218798719066407
(includes videos of fixed and actually observed behaviour ^)
Explanation:
- `CitySignal` contains three nerves (states): `WaitRed`, `WaitBlue` and `WaitOff`, which all don't really show different behavior, except the animation associated with each of them: `WaitRed` blinks red, `WaitBlue` shows constantly green and `WaitOff` is ... off.
- Usually, …
> MapObj: Implement `CitySignal`

- lib/al/Library/Camera/CameraParamMoveLimit.cpp
- lib/al/Library/Camera/CameraParamMoveLimit.h
- lib/al/Library/Camera/CameraPoser.h
This class somehow restricts camera movement to a certain area given by `MoveLimit`, listing `PlusX-Z` and `MinusX-Z` - at least that's what I'm guessing. It is specific to each individual `CameraPoser`, so multiple camera setups in the same stage could use different restricted movement areas.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/154)
> Library/Camera: Implement `CameraParamMoveLimit`

- tools/check-format.py
`check-format.py` will no longer produce warnings when using python 3.12.
Fixes #129
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/158)
> `tools/check-format.py`: Fix warnings with python 3.12

- lib/al/Library/Math/MathUtil.h
- lib/al/Project/Camera/CameraAngleSwingInfo.cpp
- lib/al/Project/Camera/CameraAngleSwingInfo.h
More camera stuff! This class is responsible for managing the slight swing movements up/down/left/right when dealing with a fixed camera. It allows slightly changing the camera direction by (default = 15°), to make it feel less static, but moves the camera back when the stick is stopped being held.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/155)
> Project/Camera: Implement `CameraAngleSwingInfo`

- lib/al/Library/Camera/ActorCameraTarget.cpp
- lib/al/Library/Camera/ActorCameraTarget.h
- lib/al/Library/LiveActor/ActorAreaFunction.h
Next in the category of "Camera stuff": A `CameraTarget` for following actors. It allows adding a `localOffset`, for example to place the target 150 units to the front of the actor, which gets adjusted according to the matrix of the actor (=> front relative to the actor, not globally). Additionally, the target can be moved along the global Y axis, usually placing the target above the actor itself.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/157)
> Library/Camera: Implement `ActorCameraTarget`

- lib/al/Library/Math/MathUtil.cpp
- lib/al/Library/Math/MathUtil.h
- lib/al/Library/Math/ParabolicPath.cpp
- lib/al/Library/Math/ParabolicPath.h
Another one of those math-heavy classes. This one allows objects to follow a `ParabolicPath`, which is often configured by just giving `start`, `end` and some `height`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/148)
> Library/Math: Implement `ParabolicPath`

- lib/al/Library/Camera/CameraTicket.h
- lib/al/Library/Camera/CameraTicketHolder.cpp
- lib/al/Library/Camera/CameraTicketHolder.h
A short class that can hold all `CameraTicket`s that are currently loaded in the stage. It also provides a small function for fetching the camera ticket belonging to a specific entrance by just comparing the `PlacementId` and `Suffix` to all currently held `Ticket`s.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/159)
> Library/Camera: Implement `CameraTicketHolder`

- src/Player/PlayerBindKeeper.h
- src/Player/PlayerJudgeLongFall.cpp
- src/Player/PlayerJudgeLongFall.h
Judges whether Mario has fallen far enough that he will be staggered upon landing.
Note that this judge also checks that:
* Mario is not dead,
* Mario is not 2D,
* The “bind keeper” is not active, and
* Mario is not in a capture.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/168)
> Player: Implement `PlayerJudgeLongFall`

- lib/al/Library/Obj/AllDeadWatcher.cpp
- lib/al/Library/Obj/AllDeadWatcher.h
This PR move Nerve definitions out of the header in order to follow decomp's code style.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/171)
> Library/Obj: Refactor `AllDeadWatcher`

- lib/al/Library/Camera/ICameraInput.h
- lib/al/Library/Camera/SimpleCameraInput.cpp
- lib/al/Library/Camera/SimpleCameraInput.h
The button mapping regarding actions on the camera is done within this class - at least by default, if SMO wouldn't override it with `ProjectCameraInput` again. Either way, this PR provides the basic definition of `ICameraInput` and its first descendant, `SimpleCameraInput`, which does the following mapping:
- RStick = camera movement
- L or R = reset
- ZL = zoom in (snapshot)
- ZR = zoom out (snapshot)
This is pretty much identical to what `ProjectCameraInput` provides, but the latter has a few more things, like rolling or moving the camera in snapshot mode.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/160)
> Library/Camera: Implement `ICameraInput` and `SimpleCameraInput`

- README.md
Thanks to `@Cookieso` on Discord, we now also know which package is required to add the `libtinfo.so.5` library to arch-based systems. This information should be added to the README.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/172)
> README: Add information about `libncurses5` on arch

- lib/al/Library/Collision/CollisionParts.h
- lib/al/Library/Collision/CollisionPartsTriangle.cpp
- lib/al/Library/Collision/CollisionPartsTriangle.h
A larger class, paving the way for some more collision-related code to be merged. `al::Triangle` intends to combine a triangle from `kcl` (`KCPrismData`) and the `CollisionPart` it is attached to, connecting it to the actor as well. For easier access, `Positions` and `Normals` are stored in a "translated" form, meaning that the actor movmement/rotation/... is applied as well, while the `KCollisionServer` only deals with local position.
Throughout this class, some code duplication has to be done, for example with the `calcAndGet[...]Normal`, `getLocalPos` and a lot of `getBaseMtx()`s. I have not found a better way to change some of them without breaking other functions. This can't properly be encapsulated in a `decomp.me`, as multiple functions play together here (fixing one might break …
> Library/Collision: Implement `Triangle`

- lib/al/Library/Bgm/BgmLineFunction.h
- src/MapObj/ChurchDoor.cpp
- src/MapObj/ChurchDoor.h
- src/Scene/ProjectActorFactory.cpp
- src/System/GameDataHolderAccessor.h
- src/Util/StageSensorMsgFunction.h
I wanted to do another actor today, so my "randomly scroll around and select one" strategy landed on this one.
Notable things about the actor itself:
- It only saves whether the door is open or not in "binary" form, there is no intermediate (amount of hits). It is considered "open" after the animation of the third hit has finished playing.
- This state is only persisted for `MoonWorldWeddingRoomStage`, meaning the church on the moon itself - not the rematch.
- Attacks are only counted when the type is "Cappy hits the wall of the door". After the first and second hit, the first 10 frames the door is "immune" to another attack.
Notable things from the programmer's side:
- The amount of hits (3) and each individual animation is hardcoded, presenting a nerve for both "open" and "close" for …
> MapObj: Implement `ChurchDoor`

- src/System/GameDataFunction.h
Those should return `bool`eans, which often just tell whether the `ChangeStageInfo.mChangeStageName` is non-empty. Nontheless, the current declaration is wrong and the return type should be adjusted. Thanks to @LynxDev2 for letting me know!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/193)
> System: Adjust return type of `tryChangeNextStage*`

- lib/al/Library/LiveActor/LiveActor.cpp
- lib/al/Library/LiveActor/LiveActor.h
- lib/al/Library/MapObj/BreakMapPartsBase.cpp
- lib/al/Library/MapObj/BreakMapPartsBase.h
- lib/al/Library/MapObj/ChildStep.cpp
- lib/al/Library/MapObj/ChildStep.h
- lib/al/Library/MapObj/FallMapParts.cpp
- lib/al/Library/MapObj/FallMapParts.h
- lib/al/Library/MapObj/FixMapParts.cpp
- lib/al/Library/MapObj/FixMapParts.h
- lib/al/Library/MapObj/FloaterMapParts.cpp
- lib/al/Library/MapObj/FloaterMapParts.h
- lib/al/Library/MapObj/RollingCubeMapParts.cpp
- lib/al/Library/MapObj/RollingCubeMapParts.h
- src/Amiibo/ItemAmiiboKoopa.cpp
- src/Amiibo/ItemAmiiboKoopa.h
- src/Enemy/EnemyStateDamageCap.cpp
- src/Enemy/EnemyStateHackStart.cpp
- src/MapObj/AnagramAlphabetCharacter.cpp
- src/MapObj/AnagramAlphabetCharacter.h
- src/MapObj/ChurchDoor.cpp
- src/MapObj/ChurchDoor.h
- src/MapObj/CitySignal.cpp
- src/MapObj/CitySignal.h
- src/MapObj/FireDrum2D.cpp
- src/MapObj/FireDrum2D.h
- src/Player/Player.cpp
- src/Player/Player.h
According to the poll from October 14th, `self` and `other` are the "best names" for `HitSensor`s in `receiveMsg` and `attackSensor` functions that we decided upon, for clarification and consistency across the repo. In this PR, all existing usages of `HitSensor`s have been adjusted to use the new names.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/196)
> Change parameter names of `HitSensor`s to `self`/`other`

- lib/al/Library/MapObj/ConveyerStep.cpp
- lib/al/Library/MapObj/ConveyerStep.h
- lib/al/Library/Placement/PlacementFunction.h
- lib/al/Project/LiveActor/ConveyerKeyKeeper.h
This PR adds `ConveyerStep` functions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/208)
> Library/MapObj: Implement `ConveyerStep`

- lib/al/Library/MapObj/RailMoveMapParts.cpp
- lib/al/Library/MapObj/RailMoveMapParts.h
- lib/al/Library/Rail/RailUtil.h
- lib/al/Library/Stage/StageSwitchKeeper.h
- src/Scene/ProjectActorFactory.cpp
This PR adds `RailMoveMapParts` functions.
According to the function map, it seems that `KeyMoveMapParts` and `ChildStep`'s nerves need to be defined in `al`.
I will make another PR to correct my mistake.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/209)
> Library/MapObj: Implement `RailMoveMapParts`

- lib/al/Library/MapObj/ChildStep.cpp
- lib/al/Library/MapObj/KeyMoveMapParts.cpp
This PR moves `ChildStep` and `KeyMoveMapParts`'s nerves in `al`
When I made #209, I realised that `ChildStep` and `KeyMoveMapParts`'s nerves need to be defined in `al`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/210)
> Library/MapObj: Refactor `ChildStep` and `KeyMoveMapParts`

- .github/workflows/compile-check.yml
- .github/workflows/progress.yml
- .github/workflows/test-compile.yml
https://github.com/actions/runner-images/issues/10636
> Rollout will begin on December 5th and will complete on January 17th, 2025.
`ubuntu-latest` as runner image will be upgraded from `22.04` to `24.04` gradually within this period, and it seems like the repo by @Fuzzy2319 has been affected first, causing build failures due to the removal of `libncurses5` from `apt`.
The simplest fix is to globally pin our `runs-on` version of all sensitive workflows to `24.04` to enforce that version for all forks, and download `libtinfo5` (as part of `libncurses5`) manually as `deb` from the ubuntu archive.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/211)
> dev: Update workflows for Ubuntu 24.04

- src/Amiibo/HelpAmiiboExecutor.h
- src/Amiibo/HelpAmiiboYoshi.h
- src/Player/Yoshi.h
https://github.com/MonsterDruide1/OdysseyDecomp/pull/215 did not run the `clang-format` and custom linting pipeline, so it went unnoticed that there were some small issues with formatting here. These are fixed in this follow-up PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/218)
> Amiibo: Fix clang-format

- lib/al/Library/Math/InOutParam.cpp
- lib/al/Library/Math/InOutParam.h
- lib/al/Library/Math/MathUtil.h
Simple one - I needed some success. This class seems to be mainly used when controlling music/sound effects.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/213)
> Library/Math: Implement `InOutParam`

- lib/al/Library/Rail/RailUtil.h
This PR adds missing const qualifiers in `RailUtil` and adds two new functions to the header merged from the header I made for a mod.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/216)
> Library/Rail: Refactor `RailUtil`

- src/Item/CoinCollectDummy.cpp
- src/Item/CoinCollectDummy.h
- src/Item/CoinCollectHintState.h
This is used in HelpAmiiboCoinCollect. I'm stuck in that one so for now I will implement all coin collect variants.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/221)
> item: Implement CoinCollectDummy

- .devcontainer/Dockerfile
- .github/workflows/compile-check.yml
- .github/workflows/lint.yml
- README.md
- flake.lock
- flake.nix
Updating some of the underlying packages for all NixOS users. In the process, also disable `ansiwrap` from the python packages, because it is now marked as `broken` (after 7 years not being maintained) - it's still listed in the [`pyproject.toml` of asm-differ](https://github.com/simonlindholm/asm-differ/blob/89e9c7044039ed18117ea45b6e1f551da49172cc/pyproject.toml#L13), but I'll ask if that's even still required - or if this package has been long unused and can just be removed from here as well.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/237)
> dev: Update `nixpkgs` to `nixos-unstable`

- src/Npc/AchievementHolder.cpp
- src/System/GameDataHolderAccessor.h
- src/System/GameDataHolderWriter.h
- src/Util/ClothUtil.cpp
As usages of `GameDataHolderWriter` also create an instance of `Accessor` first, it seems like the usage order is the other way around - `Writer` makes use of `Accessor`. After a bit of discussion on the Discord channel (https://discord.com/channels/774687602996936747/1327403202768797779), inheritance mostly seems the way to go - although we cannot tell it apart from `Writer` containing a single member variable (`Accessor`) with an inlined constructor.
During the discussion, I also learned about defining [user-defined conversion functions](https://en.cppreference.com/w/cpp/language/cast_operator) - and its implicit variant, allowing `mData` of the accessor being accessed without always specifying the `mData` or its getter - which seems to be a great way to reduce boilerplate code around …
> System: Flip inheritance order of `GameDataHolderAccessor`/`Writer`

- lib/al/Library/LiveActor/ActorAnimFunction.h
Adds/Removes `const` to `al::LiveActor*`s within this file where they were previously missing, or added too much. This resulted in calls to this function being directed to the wrong symbol, which showed up as mismatch in for example #239.
Fixes #240
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/257)
> Library/LiveActor: Fix `const` on parameters in `ActorAnimFunction`

- src/MapObj/WorldMapParts.cpp
Implements a local function I named `processSubActors` in `WorldMapParts`, which loops through an actor's sub actors and runs `al::invalidateOcclusionQuery` on it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/244)
> MapObj: Implement a local function in `WorldMapParts`

- flake.nix
As @LynxDev2 reported, `clang-format` is currently broken/inconsistent on NixOS - this is because some update changed some default option, which we currently do not want to change. Thus, the easiest option is just keeping all `clang`-versions on version `14`, which is also the max version on Ubuntu `22.04`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/262)
> dev: Pin `clang`-versions to `14`

- src/Item/CoinCollectHolder.h
- src/MapObj/CoinCollectHintObj.cpp
- src/MapObj/CoinCollectHintObj.h
This one required more code in the header than the implementation. Is used in CoinCollectHolder.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/267)
> MapObj: Implement `CoinCollectHintObj`

- lib/al/Library/Nerve/NerveSetupUtil.h
- src/Npc/TiaraEyes.cpp
- src/Npc/TiaraEyes.h
`TiaraEyes` is a simple class with a bunch of repeated functions. However, this is the first class to have an implemented `executeOnEnd` nerve!
I created a `NERVE_END_IMPL_` and `NERVE_END_IMPL` to handle it. Maybe it should be renamed `NERVE_ON_END_IMPL` or `NERVE_WITH_END_IMPL`?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/272)
> Npc: Implement `TiaraEyes`

- tools/check-format.py
I wrote down that this issue exists back in March 2024 - and then forgot about it. This PR finally fixes this one wrong error message.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/283)
> lint: Fix typo in includes check

- .github/workflows/compile-check.yml
Fixes #60 
So far, the `compile-check` workflow did not output its error messages, because `tools/check` failed with a non-zero exit code in these circumstances, so the remainder of the step would not be executed. By adding `|| true` to it, failing return codes are ignored. Additionally, by piping the error to a file and reading it back with `cat`, newlines are preserved. Rust shows its stack trace by default when using `bail!` to exit a program, so we're also cutting that and the remainder of the (multiline) message away using `sed`. `\f` (form feed symbol) is used as a temporary replacement for `\n` here, to allow multi-line replacements in `sed` without fancy commands.
- - - …
> workflow: Fix error outputs for `compile-check`

- lib/al/Library/Collision/CollisionPartsTriangle.cpp
- lib/al/Library/Collision/CollisionPartsTriangle.h
- tools/check-format.py
On the way to pulling in more collision-specific code, another pretty important class is `HitInfo`. It stores the result(s) of collisions with some extra meta-data that can be used to appropriately react to the collision at hand.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/182)
> Library/Collision: Implement `al::HitInfo` and variants

- src/MapObj/TransparentWall.cpp
- src/MapObj/TransparentWall.h
- src/Util/ActorDimensionKeeper.h
Just a standard invisible wall that you don't see everywhere in the game.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/276)
> MapObj: Implement `TransparentWall`

- src/MapObj/PeachWorldTree.cpp
- src/MapObj/PeachWorldTree.h
These exist in Mushroom Kingdom's SM64 Mario costume room. Here's a glitch with them since you can move your camera position far using snapshot mode within a single frame: https://www.youtube.com/watch?v=_czg_7JYH_s
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/278)
> MapObj: Implement `PeachWorldTree`

- lib/al/Library/LiveActor/ActorInitInfo.h
- lib/al/Library/LiveActor/ActorMovementFunction.h
- lib/al/Library/MapObj/SlideMapParts.cpp
- lib/al/Library/MapObj/SlideMapParts.h
- src/Scene/ProjectActorFactory.cpp
This PR adds `SlideMapParts` functions
I didn't manage to get `SlideMapParts::init` matching. It seems that it uses `makeQT` but with different axis.
This class is a leftover from SM3DW
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/288)
> Library/MapObj: Implement `SlideMapParts`

- src/Enemy/SenobiLeaf.cpp
Fixes a regswap in `SenobiLeaf::registerToHost` by using an if/else instead of a ternary. I can't believe I didn't try this before!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/292)
> Enemy: Match `SenobiLeaf::registerToHost`

- src/MapObj/FurnitureStateWait.cpp
- src/MapObj/FurnitureStateWait.h
- tools/check-format.py
Wait state calls for beds and chairs. Probably used when Mario sits or sleeps on things.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/280)
> MapObj: Implement `FurnitureStateWait`

- flake.nix
- lib/al/Library/LiveActor/ActorSensorMsgFunction.h
- lib/al/Library/Nature/NatureUtil.h
- lib/al/Library/Stage/StageSwitchKeeper.h
- src/Enemy/Togezo.cpp
- src/Enemy/Togezo.h
- src/Util/SensorMsgFunction.h
I was searching on Discord and found a zip of @CraftyBoss's Togezo decomp. Believe it or not, people really decomped this game before the reorganization. I've went around and modernized it and now it's 100% matching (thanks everyone in discord for helping with that.)
This is the weirdest class I've dealt with in the way that Nintendo wrote this code. A Nintendo developer really struggled to implement this actor. Here's some examples on the cursed code going on:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/268)
> Enemy: Implement `Togezo` (by CraftyBoss)

- lib/al/Library/Layout/LayoutActionFunction.h
- lib/al/Library/Message/MessageHolder.h
- src/Layout/WindowConfirmData.cpp
- src/Layout/WindowConfirmData.h
Implements `WindowConfirmData`. Also completes the `LayoutActionFunction` header.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/274)
> Layout: Implement `WindowConfirmData`

- lib/al/Library/Placement/PlacementFunction.h
- lib/al/Library/Placement/PlacementId.h
- lib/al/Project/LiveActor/SupportFreezeSyncGroup.cpp
- lib/al/Project/LiveActor/SupportFreezeSyncGroup.h
This PR adds `SupportFreezeSyncGroup` functions.
~`SupportFreezeSyncGroup::regist` doesn't check if `mActorCount` is greater than `mMaxActorCount` which can lead in a buffer overflow in this case.~
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/294)
> Project/LiveActor: Implement `SupportFreezeSyncGroup`

- lib/al/Library/MapObj/SwitchDitherMapParts.cpp
- lib/al/Library/MapObj/SwitchDitherMapParts.h
- lib/al/Library/Model/ModelCtrl.h
- lib/al/Library/Obj/ActorDitherAnimator.h
- lib/al/Library/Thread/FunctorV0M.h
- src/Scene/ProjectActorFactory.cpp
This PR:
- adds `SwitchDitherMapParts` functions.
- rename `mFunctor` by `mFunctPointer` in `FunctorV0M`
- adds padding in `ModelCtrl`
- adds an incomplete declaration for `ActorDitherAnimator`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/298)
> Library/MapObj: Implement `SwitchDitherMapParts`

- src/Item/CoinCollect2D.cpp
- src/Item/CoinCollect2D.h
- src/MapObj/CapMessageShowInfo.h
- src/Scene/ProjectActorFactory.cpp
One of the biggest classes for coin types. This one utilizes most of the previous implementations.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/289)
> item: Implement CoinCollect2D

- lib/al/Library/Nature/NatureUtil.h
- src/Player/PlayerJudgeDiveInWater.cpp
- src/Player/PlayerJudgeDiveInWater.h
If this judge triggers, the player automatically enters a diving animation/state. It only seems to trigger when jumping off very high cliffs/objects, as Mario needs to have a distance of at least 1500 units (+160 for his own height) to the water surface.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/310)
> Player: Implement `PlayerJudgeDiveInWater`

- src/MapObj/BlinkRateCalculator.cpp
- src/MapObj/BlinkRateCalculator.h
Oops, I pushed this to MonsterDruide1's remote instead of my fork. Implements an unused class named `BlinkRateCalculator`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/299)
> MapObj: Implement `BlinkRateCalculator`

- src/MapObj/CapBomb.cpp
- src/MapObj/CapBomb.h
- src/Scene/ProjectActorFactory.cpp
- src/Util/SensorMsgFunction.h
Used somewhere in the game...
It initializes a test layout & parts but doesn't use them.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/304)
> MapObj: Implement `CapBomb`

- src/Util/SequentialUtil.cpp
- src/Util/SequentialUtil.h
Most likely utility functions for koopa freerunning and timers.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/301)
> Util: Implement SequentialUtil

- lib/al/Library/Nature/NatureUtil.h
- lib/al/Library/Nature/WaterSurfaceFinder.cpp
- lib/al/Library/Nature/WaterSurfaceFinder.h
Small helper class to locate the nearest water surface looking down from the given actor. Sadly, because `updateLocal` is not matching, none of the other functions for updating the result matches either.
https://decomp.me/scratch/zHEdm
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/317)
> Library/Nature: Implement `WaterSurfaceFinder`

- lib/al/Library/LiveActor/ActorSensorFunction.h
- lib/al/Library/MapObj/SupportFreezeSyncGroupHolder.cpp
- lib/al/Library/MapObj/SupportFreezeSyncGroupHolder.h
This PR adds `SupportFreezeSyncGroupHolder` functions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/320)
> Library/MapObj: Implement `SupportFreezeSyncGroupHolder`

- src/System/SphinxQuizData.cpp
- src/System/SphinxQuizData.h
Data object for answers for the Sphinx's questions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/324)
> System: Implement `SphinxQuizData`

- lib/al/Library/MapObj/WheelMapParts.cpp
As #319 cleaned up include-dependencies between various headers in `Library/Nerve`, `NerveUtil.h` should now be included manually in every file. As this PR was created and merged around the same time as #325, the latter PR did not add this include yet, causing a compiler error on the workflows.
In this PR, the missing include is added, to fix workflows again.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/333)
> Library/MapObj: Include `NerveUtil`

- src/Player/PlayerActionSlopeSlideControl.h
- src/Player/PlayerStateSlope.cpp
- src/Player/PlayerStateSlope.h
- src/Util/PlayerCollisionUtil.h
Even though this looks like a simple class that doesn't contain much code and logic, this PR marks a milestone - we finally have enough dependencies and related headers to work on player movement classes. This might make the project more interesting to game scientists and tech researchers as well, at least those that are able to read the code - the logic is often not as simple as one might imagine.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/330)
> Player: Implement `PlayerStateSlope`

- .github/files/HeadersCMakeLists.txt
- .github/scripts/copy-headers.sh
This makes it so that the workflow that deploys the headers to `OdysseyHeaders` also adds a `CMakeLists.txt` that has a header only library. This way projects that use the headers repo can just "link" the library instead of having to include each directory manually.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/332)
> Workflow: Add CMakeLists to headers repo job

- src/Player/PlayerDamageKeeper.cpp
- src/Player/PlayerDamageKeeper.h
``PlayerDamageKeeper``:
- Adds 3 function declarations: ``activatePreventDamage``, ``dead`` and ``damage``.
``NerveSetupUtil``:
- New Macro to better define so called "Actions" (Nerve Functions) for both the definition and declaration.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/18)
> Player: Add partial `PlayerDamageKeeper`

- lib/al/Project/HitSensor/HitSensor.h
- lib/al/Project/HitSensor/SensorHitGroup.cpp
This PR implements the two missing functions of `SensorHitGroup`: `remove` and `clear`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/347)
> Project/HitSensor: Finish `SensorHitGroup` implementation

- src/Item/CoinRotateCalculator.cpp
- src/Item/CoinRotateCalculator.h
This branch has been sitting for a few weeks. I can't match the update function.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/314)
> item: Implement CoinRotateCalculator

- src/Boss/BossForest/BossForestWander.cpp
- src/Boss/BossForest/BossForestWander.h
Implements `BossForestWander`. Because the nerves are HostType, there's a mismatching `HostTypeNrvMove` function until `BossForestBlock` is decompiled.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/315)
> Boss/BossForest: Implement `BossForestWander`

- src/Player/PlayerAnimFrameCtrl.cpp
- src/Player/PlayerAnimFrameCtrl.h
This class is used to keep track of the current frame within an animation. It can handle looping animations (`mIsActionRepeat`) and changing the framerate of animations (`mRate`), resulting in faster or slower playback.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/318)
> Player: Implement `PlayerAnimFrameCtrl`

- lib/al/Library/Demo/DemoDirector.h
- lib/al/Library/LiveActor/ActorSceneFunction.cpp
- lib/al/Library/LiveActor/ActorSceneFunction.h
- lib/al/Library/Scene/SceneStopCtrl.h
- lib/al/Library/Screen/ScreenCoverCtrl.h
This PR implements `ActorSceneFunction`, a very simple utility object for interacting with the current scene through a `LiveActor`. I decided to put `ActorSceneInfo::ActorSceneInfo() = default;` in that cpp file too, since that's better than making another file for that one line imo
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/346)
> Library/LiveActor: Implement `ActorSceneFunction`

- lib/al/Library/Camera/CameraResourceHolder.cpp
- lib/al/Library/Camera/CameraResourceHolder.h
- lib/al/Library/Camera/CameraTicketId.h
- lib/al/Library/Placement/PlacementId.h
"Hey! Let's implement a simple class before sleeping." - I thought. Which was a mistake.
This class is responsible for caching `CameraParam.byml`s and `InterpoleParam.byml`s, although only the former is exposed. As `[try]FindCameraResource`, the functions with more detailed return type, are not used outside of this class itself, it seems like `InterpoleParam.byml` is not fetched from this class again.
Most of this file was straight-forward to implement, with the exception of `SafeString`-magic. Here, this is capsuled into `getStageName`: `endsWith` is being inlined here, meaning that in total 4 `calcLength`s end up in this file, which was ... not easy to map to one of the existing functions again. The `paramType` attribute of `tryFindParamResource` seems a bit weird (`0`, `2`, `anything …
> Library/Camera: Implement `CameraResourceHolder`

- lib/al/Library/Camera/CameraShaker.cpp
- lib/al/Library/Camera/CameraShaker.h
Another camera-related class.
Within `CameraShaker::startShakeByIndex`, I feel like it's not quite intended to create a copy of `ShakeInfo shake2 = shake;`, but I found that the best way to get it matching. Feel free to test around/try other things as well:
https://decomp.me/scratch/asjPP
Either way, interesting fact from the code: If the currently running CameraShake is considered "greater than" the one that should be started now, the new one will be ignored. For the comparison, the following criteria are considered, in-order:
- `mStrength`
- a shake with no determined "runtime" (steps/frames/seconds) is considered "less than" one with defined length, probably to rank one-off shakes more important than constant background shakes
- `mSteps`
- `mDirection`: Shaking in both directions is …
> Library/Camera: Implement `CameraShaker`

- lib/al/Library/Nature/FireSurfaceFinder.cpp
- lib/al/Library/Nature/FireSurfaceFinder.h
- lib/al/Library/Nature/NatureUtil.h
- lib/al/Library/Nature/WaterSurfaceFinder.cpp
- lib/al/Library/Nature/WaterSurfaceFinder.h
Apparently surface properties are another class. We don't have other surface objects to verify that this struct belongs to other object. But fixes mismatches of this file.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/339)
> Library/Nature: Fix WaterSurfaceFinder and Implement FireSurfaceFinder

- .github/workflows/rebase-requirement.yml
In the last PR, I put `master` as the branch to checkout to for the list file without knowing that would cause problems. Hopefully changing that to `origin/master` fixes that and if it doesn't the `|| true` should prevent the workflow from failing because of that
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/381)
> Rebase workflow: Quick fix

- lib/al/Library/Controller/IUsePadDataReader.h
- lib/al/Library/Controller/IUsePadDataWriter.h
- lib/al/Library/Controller/PadDataPack.h
- lib/al/Library/Resource/Resource.h
- lib/al/Project/Controller/PadDataArcReader.cpp
- lib/al/Project/Controller/PadDataArcReader.h
an unused class. this reads input data from a `.bin` file as an array of 0x18-byte frames (of type `PadDataPack`), and sends it to `al::ReplayController` to be applied to the controller. this does get used in 3D world, so perhaps it's a relic from that. the `IUsePadDataReader`/`Writer` classes are almost nonexistent in the binary, but i got the `Reader`'s functions from the class in this PR, and the `Writer`'s functions i deduced from various `al::ReplayController` functions (namely `calc`, `startRecord` and `endRecord`, with the `open`/`close` copied from the `Reader` class, rather than just naming them `start`/`end` or something like that).
- - - …
> `Project/Controller`: implement `al::PadDataArcReader`

- src/Amiibo/HelpAmiiboCountUpCoin.cpp
- src/Amiibo/HelpAmiiboDirector.h
- src/Amiibo/HelpAmiiboExecutor.h
- src/Amiibo/HelpAmiiboLifeMaxUpItem.cpp
- src/Amiibo/HelpAmiiboLifeMaxUpItem.h
- src/Item/LifeMaxUpItem.h
- src/Item/LifeMaxUpItem2D.h
- src/Scene/ProjectActorFactory.cpp
I couldn't implement `HelpAmiiboDirector `so I went with the next best thing. Some header dependencies. This is a relatively small class but required many headers. Including changing the `HelpAmiiboType` enum, the entries of this enum don't refer to the class type, instead they indicate which amiibos might trigger that loot when an amiibo is loaded.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/388)
> Amiibo: Implement HelpAmiiboLifeMaxUpItem

- src/Enemy/Togezo2D.cpp
- src/Enemy/Togezo2D.h
- src/Scene/ProjectActorFactory.cpp
- src/Util/ActorDimensionKeeper.h
This PR implements `Togezo2D`, the 2D version of the spiny enemy
I know the discussion about inline member functions is still in progress, but I still decided to keep `checkFacingTarget` as another example for #343, it should maybe be made private though 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/372)
> Enemy: Implement `Togezo2D`

- lib/al/Library/Action/ActorActionKeeper.h
- lib/al/Library/LiveActor/ActorActionFunction.cpp
- lib/al/Library/LiveActor/ActorActionFunction.h
- lib/al/Library/LiveActor/ActorAnimFunction.h
- lib/al/Library/MapObj/FallMapParts.cpp
- lib/al/Library/MapObj/GateMapParts.cpp
- lib/al/Library/Nerve/NerveActionCtrl.h
- lib/al/Library/Obj/KeyMoveFollowTarget.cpp
- lib/al/Project/Action/ActionAnimCtrl.h
- lib/al/Project/Action/ActionSeCtrl.h
Decompiled another utility function file. This one is focused on `Action`s, both in terms of animations and `NerveAction`s. With these implemented, the checker complained about four wrong calls throughout some files (`startAction` called instead of `startNerveAction`), so these have been fixed here as well.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/359)
> Library/Action: Implement `ActorActionFunction`

- .clang-format
- .github/workflows/lint.yml
- Contributing.md
- lib/al/Library/Collision/CollisionPartsTriangle.h
- lib/al/Library/Execute/ExecuteDirector.cpp
- lib/al/Library/Nerve/NerveSetupUtil.h
Ubuntu 24.04 supports up to version 19 at the moment, but the `clang-format-lint-action` workflow only supports version 18, so i updated it to that. 
in `CollisionPartsTriangle.h`, `clang-format` wants to make the references align to the middle (i.e. with a space on either side of the `&`). this is fixed if the `::` is removed from the start of each of the `operator` functions, but this causes a compile error, so i've just disabled `clang-format` for those two lines. would it be better to just accept the middle alignment there? i tried using the `ReferenceAlignment: Left` rule but it made no difference, and no other rule seems like it would be of any help.
- - - …
> workflow: update `clang-format` to version 18

- lib/al/Library/Sequence/Sequence.h
- lib/al/Library/System/GameSystemInfo.h
- src/Sequence/HakoniwaSequence.cpp
- src/Sequence/HakoniwaSequence.h
- src/System/GameSystem.h
also forward declared some classes instead of unnecessarily including their headers
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/382)
> `System`: fix styling of `GameSystemInfo` member variables

- lib/al/Library/Scene/SceneObjUtil.h
- src/Amiibo/HelpAmiiboCoinCollect.cpp
- src/Amiibo/HelpAmiiboCoinCollect.h
- src/Item/CoinCollectHolder.h
This class has been in the burner for quite a few weeks. From the start to bottom the code was harsh to implement and look at. HelpAmiiboCoinCollect::activate was very hard. It contains a lot of duplicated code that resulted in very weird branching.
This implementation feels like it can get a lot cleaner than this.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/407)
> Amiibo: Implement `HelpAmiiboCoinCollect`

- src/Player/PlayerAnimator.h
- src/Player/PlayerStateHipDrop.cpp
- src/Player/PlayerStateHipDrop.h
- src/Player/PlayerTrigger.h
- src/Util/ObjUtil.h
The player, doing a ground pound. Pretty simple, as the player has almost no control over Mario during this action, only again after he hits the ground.
Interesting things:
- `ECollisionTrigger_val1` can trigger `HipDropReaction`-animation and causes `isLandTrigger` to return `true`, but doesn't necessarily land on the ground (depending on what triggers this collision attribute)
- If the ground is not `isOnRunAngle` (angled outside of `StandAngleMin` and `StandAngleMax` depending on velocity, so tilted by more than 60/70 degrees), the action is immediately killed instead of waiting for the ground pound animation to end, which might be faster during speedruns
Also, a thing I did a larger investigation on was the `isLandingWeak` variable: If the ground pound is interrupted by …
> Player: Implement `PlayerStateHipDrop`

- README.md
This is a very simple PR that changes the recommended ubuntu version from 22 to 24 since 22 doesn't have the `clang-format` version now required after #393. I also removed the outdated `from the re-organization` section
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/416)
> README: Change recommended ubuntu version and remove outdated section

- .github/scripts/push-headers.sh
Earlier today I noticed that @german77's commits weren't being pushed to [OdysseyHeaders](https://github.com/MonsterDruide1/OdysseyHeaders) correctly. This is because their git name (`Narr The Reg`) has spaces which causes it to be interpreted as multiple args when setting the username. This PR fixes that by simply putting `$AUTHOR_NAME` in quotes
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/420)
> Copy-headers workflow: Fix pushing commits with a git username with spaces 

- lib/al/Library/Camera/CameraViewCtrlGyro.h
- lib/al/Library/Camera/CameraViewCtrlPause.cpp
- lib/al/Library/Camera/CameraViewCtrlPause.h
- lib/al/Library/Camera/CameraViewCtrlScene.cpp
- lib/al/Library/Camera/CameraViewCtrlScene.h
Add GyroCameraCtrl header, and just as the title says, the doc also has this change now. GyroCameraCtrl outweights the other 3 in terms of code size, and the three are most likely not used together, + the names add up. so i wanted to split this.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/427)
> Libary/Camera: Add `CameraViewCtrl*`

- src/ModeBalloon/TimeBalloonStateShowAchievement.cpp
- src/ModeBalloon/TimeBalloonStateShowAchievement.h
A random number generator picked this one- and there's a lot of weird stuff going on. A bunch of unused member variables are created (including two `WStringTmp`s, which don't even make sense as member variables), and the `Close` nerve doesn't have a `NERVE_IMPL` macro. They must have commented a bunch of the code out and left it like that for release (since balloon world released as an update). I wonder what it looks like in 1.2.0.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/431)
> ModeBalloon: Implement `TimeBalloonStateShowAchievement`

- lib/al/Library/Collision/CollisionPartsTriangle.cpp
- lib/al/Library/Collision/CollisionPartsTriangle.h
- src/Player/CollidedShapeResult.cpp
- src/Player/CollidedShapeResult.h
- tools/check-format.py
Requires #404 to be merged first.
Also pretty simple. Note the `sead::StorageFor` being used here, due to the constructor behaving kind-of weird: Instead of calling the constructor for each `HitInfo` directly, it first calls `memset` to set the entire area to `0`, *then* calls the constructor. I was only able to re-create that using this class. Additionally, should *not* be implemented like this in the `cpp`, as it would end up linking in the wrong place - until `CollisionShapeKeeper` is implemented, it should remain like this though, to ensure this function is generated and can be checked.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/406)
> Player: Implement `CollidedShapeResult`

- src/Player/PlayerActionSlopeSlideControl.cpp
- src/Player/PlayerActionSlopeSlideControl.h
- src/Util/ObjUtil.h
This class is used to control all or part of Mario's movement during sliding (mostly) uncontrollably, and while rolling. Working with floating-point calculation functions of this size is ... quite painful, but all functions have been matched here. Some things (especially within `update`) look quite ugly, so I'm happy to take suggestions on how to simplify code further or improve other stuff - feel free to try by yourself first to verify which changes are possible and which destroy a match: https://decomp.me/scratch/ZqxG4
This PR is currently marked as draft because it should wait for #330 to be merged first, which changes around some stuff within the header of this class, so this will cause merge conflicts if not cleaned up before.
- - -
This change is [<img …
> Player: Implement `PlayerActionSlopeSlideControl`

- lib/al/Library/Base/StringUtil.h
- lib/al/Library/Placement/PlacementFunction.cpp
- lib/al/Library/Placement/PlacementFunction.h
This PR contains `164` matched functions equivalent to `0.219%` of progress. Here, I have implemented all functions listed under `al/Library/Placement/PlacementFunction.o`, which are used by actors to get individual attributes from `PlacementInfo` and `ActorInitInfo` as well as `AreaInitInfo`.
Only one function is mismatching: `tryGetRotate(sead::Vector3f* rotate, const PlacementInfo& placementInfo)` mismatches during its matrix calculations for getting a quaternion out of two matrices. It can be checked here: https://decomp.me/scratch/towGQ
Additionally, three changes within `sead` are required to match the functions implemented correctly in here.
1. https://github.com/open-ead/sead/pull/152 - `Quat::setRPY`
2. https://github.com/open-ead/sead/pull/153 - `Matrix34::makeSRT`
3. `makeRT` …
> Library/Placement: Implement `PlacementFunction`

- lib/al/Library/Placement/PlacementFunction.cpp
Casting is required here, because otherwise most of them would just trigger a recursive call - which obviously generates wrong code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/441)
> Library/Placement: Fix builds on `PlacementFunction`

- src/Layout/DecideIconLayout.h
- src/Scene/HintPhotoLayoutHolder.cpp
- src/Scene/HintPhotoLayoutHolder.h
Minor fix. Value is passed as reference not a pointer.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/448)
> Layout: Fix `DecideIconLayout` constructor

- lib/al/Library/Controller/PadRumbleFunction.cpp
- lib/al/Library/Controller/PadRumbleFunction.h
- lib/al/Library/Layout/LayoutActor.h
At the time of writing this PR the word "Rumble" appears 460 times. Even then someone had the audacity of naming each member of `PadRumbleParam` with rumble.
This PR fully implements this header and fulfills one of the requirements of the list. If every function looks identical take some rest while reviewing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/459)
> Controller: Implement `PadRumbleFunction`

- lib/al/Library/Framework/GameFrameworkNx.h
the params of `createInfLoopChecker` are unclear as they aren't used in the game (presumably `#ifdef`ed out).
the name `mDrawReadyEvent` comes from the fact that `present_` (which i believe does something on another thread, `Presentation Thread`, based on `presentAsync_`) sets this signal, and after `procCalc_` is run, this signal is waited for before calling `procDraw_`. would make sense if it's to do with like, making sure the frame is drawn to the screen before messing with the frame buffer again.
i originally had named `mDisplayList` like `mCommandDisplayList`, and its associated `ControlMemory` as `mCommandControlMemory`, based on the fact that they're initialised with names of `コマンド０` and `コマンド１` ("command 0" and "command 1"). i'm not totally sure on those names, and GRA told me …
> `Library/Framework`: add `al::GameFrameworkNx` header

- src/MapObj/Souvenir.cpp
- src/MapObj/Souvenir.h
- src/Scene/ProjectActorFactory.cpp
Actor for souvenirs.
This has a regswap in `Souvenir::init` that seems similar to the one in [`al::BackHideParts::init`](https://github.com/MonsterDruide1/OdysseyDecomp/blob/f7ca52cd2d3a1d9e8eb3cbc0892dfa00f3a0766d/lib/al/Library/MapObj/BackHideParts.cpp#L43).
[The decompme for `Souvenir::init` is here.](https://decomp.me/scratch/8qJEm)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/458)
> MapObj: Implement `Souvenir`

- lib/al/Library/Placement/PlacementFunction.cpp
This workaround isn't needed anymore with the changes of https://github.com/open-ead/sead/pull/178
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/470)
> Library/Placement: Remove makeRT workaround

- lib/al/Library/Obj/PartsModel.cpp
I think I'm having a déjà vu. Fixes updatePose thanks to new sead changes https://github.com/open-ead/sead/pull/178
Special note on this one.  Pose matrix multiplication is inverted compared to #469 .  One of these must be wrong as` a*b` is not the same as` b*a`. I'm not well versed enough but I think EnemyCap is the wrong one.
`poseMatrix = rotationMatrix * translationMatrix` vs `poseMatrix = translationMatrix* rotationMatrix `
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/471)
> Library/Obj: Fix PartsModel::updatePose

- src/Player/PlayerJudgeStartWaterSurfaceRun.cpp
- src/Player/PlayerJudgeStartWaterSurfaceRun.h
First starting to run on water apparently has a different judge. It requires:
- be forced to run (=> rocket flower)
- water surface found below the player
- player must be moving downwards (as determined by gravity)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/475)
> Player: Implement `PlayerJudgeStartWaterSurfaceRun`

- src/Player/PlayerJudgeWaterSurfaceRun.cpp
- src/Player/PlayerJudgeWaterSurfaceRun.h
Another simple `Judge` that determines whether you can run on water:
- Water surface must be found below the player
- either be forced to run (=> rocket flower), or have a speed of more than `DashFastBorderSpeed`, which is `20` by default
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/473)
> Player: Implement `PlayerJudgeWaterSurfaceRun`

- src/Player/PlayerStateNormalWallJump.h
- src/Player/PlayerStateNormalWallSlide.h
- src/Player/PlayerStateWallAir.cpp
- src/Player/PlayerStateWallAir.h
A "meta-state", which either passes execution to `PlayerStateNormalWallJump` or `PlayerStateNormalWallSlide`, depending on the current action. Because of this, it contains very little code/logic itself - the actual control logic is tucked away in those two states instead.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/476)
> Player: Implement `PlayerStateWallAir`

- src/Player/PlayerJudgeStartRun.cpp
- src/Player/PlayerJudgeStartRun.h
- src/Util/PlayerCollisionUtil.h
Simple judge that checks whether a `Run` can/should be started. It checks the following conditions in given order:
1. If the player is in-air (not touching ground), no run can be started.
2. If the player is forced to run (=> rocket flower), a run is started.
3. If the player is stunned ("force land"), no run can be started.
4. If the player holds a directional input or is on a `Skate` ground with sufficient velocity (`0.5`), a run is started.
The `judge` function is implemented a bit weirdly towards the end. I was not able to find a better match.
`decomp.me` of the situation: https://decomp.me/scratch/qeI1M
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/48 …
> Player: Implement `PlayerJudgeStartRun`

- src/Player/CapTargetInfo.cpp
- src/Player/CapTargetInfo.h
Needed by HackFork. Requires https://github.com/open-ead/sead/pull/178 for all functions to match. Most names come from `CapTargetInfoFunction::initIterCapTargetInfo` although there are quite many variables that are simply not used. It might share a common struct with another class.
This also double checks that EnemyCap has a mistake in the poseMatrix as this matches with PartsModel.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/477)
> Player: Implement `CapTargetInfo`

- src/Player/PlayerFunction.h
- src/Player/PlayerStateAutoDash.cpp
- src/Player/PlayerStateAutoDash.h
Unused player state. It's too early to get working on the actual player without a bunch of hooks, and I did the hooks, and it looks comical because Mario's animation speed is calculated differently compared to normal actors. I didn't take a video and now my code is buried around a moving skeleton, oops.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/504)
> Player: Implement `PlayerStateAutoDash`

- lib/al/Library/Collision/Collider.h
- lib/al/Library/Collision/CollisionPartsKeeperUtil.h
- lib/al/Library/LiveActor/ActorMovementFunction.cpp
- lib/al/Library/LiveActor/ActorMovementFunction.h
- lib/al/Library/LiveActor/ActorParamMove.h
- lib/al/Library/MapObj/SlideMapParts.cpp
- src/Enemy/FlyerStateWander.cpp
- src/Enemy/Togezo2D.cpp
A multi-week journey of implementing this class finally comes to an end.
With 1780 lines (at the time of creating this PR), `ActorMovementFunction.cpp` is by far the largest non-autogenerated file within this project, followed by `PlacementFunction` with 1177 lines.
Requires the following `sead` PRs to be merged first:
- https://github.com/open-ead/sead/pull/173
- https://github.com/open-ead/sead/pull/174
All functions are matching. There are some `TODO` notes about possible additional functions in `sead` that could help making the code cleaner, but as they are not required very commonly, these are probably out-of-scope for this PR and can be worked on some time in the future.
Two bugs are located in this code, marked with `BUG`:
1. `walkAndTurnPoseToDirection` uses `forceFront` instead …
> Library/LiveActor: Implement `ActorMovementFunction`

- src/MapObj/MeganeMapParts.cpp
- src/MapObj/MeganeMapParts.h
- src/Scene/ProjectActorFactory.cpp
Another random class. This one is used for the appearing/disappearing platforms in the stages featuring `Megane` (Moe-Eye) - they appear and disappear along with the player being able to see `OddSpace` (having sunglasses on), and animate switching between those in either 30 or 40 frames by setting a shader parameter.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/514)
> MapObj: Implement `MeganeMapParts`

- lib/al/Project/Draw/GpuPerf.h
Digging in [old messages](https://discord.com/channels/774687602996936747/774703217325244426/954234805229322321) shows that @Sanae6 did a very simple version of this header once.
I did it again, but clean.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/525)
> Project/Draw: Add `GpuPerf`

- lib/al/Library/LiveActor/ActorActionFunction.cpp
- lib/al/Library/LiveActor/ActorPoseUtil.cpp
- lib/al/Library/Matrix/MatrixUtil.cpp
- src/Npc/BirdPlayerGlideCtrl.cpp
No new implementations. Just replacing old instances with new syntax that result in cleaner code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/533)
> all: Replace intances of mtx.getBase(vec, n) with mtx.getBase(n)

- src/Enemy/KaronWing.cpp
- src/Enemy/KaronWing.h
- src/Enemy/KaronWingStateHack.h
- src/Scene/ProjectActorFactory.cpp
Based on a message by @fruityloops1 on the modding discord (https://discord.com/channels/774687602996936747/774688454000246815/1356519120694284399), I finished implementing this class.
Currently, two mismatches are left:
1. `KaronWing::init` mismatches during the creation of `EnemyStateSwoonInitParam` (https://decomp.me/scratch/CDB2W)
2. `KaronWing::control` mismatches because the stack cleanup pattern is at the wrong location (https://decomp.me/scratch/72Cld)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/501)
> Enemy: Implement `KaronWing`

- lib/al/Library/Action/ActorActionKeeper.h
- lib/al/Library/Effect/EffectKeeper.h
- lib/al/Library/LiveActor/LiveActor.cpp
- lib/al/Library/LiveActor/LiveActor.h
- lib/al/Library/Model/ModelKeeper.h
- lib/al/Library/Screen/ScreenPointKeeper.h
- lib/al/Library/Shader/ActorOcclusionKeeper.h
- lib/al/Project/Clipping/ClippingFarAreaObserver.h
- lib/al/Project/Clipping/ClippingFunction.h
This PR implements the remaining member functions of the `LiveActor` class.
Some code could probably be shared between these functions through an `inline` member function, but I wasn't sure what parts should be separate functions (if any). Also, suggestions for proper names for the `ModelKeeper` `bool`s are appreciated
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/546)
> Library/LiveActor: Finish `LiveActor.o` implementation

- src/Player/PlayerActorBase.cpp
- src/Player/PlayerActorBase.h
- src/Util/ObjUtil.h
The base class of all player objects in the game. It defines a lot more "interface" (virtual functions), but only one relevant function: `receivePushMsg` handles push messages and moves the player by the specified amount to "resolve" the hit.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/556)
> Player: Implement `PlayerActorBase`

- lib/al/Library/Demo/DemoFunction.h
- tools/check-format.py
As noted in #561 the linter doesn't work because is searching for a namespace after a "(", coma or space. In this case is the first thing on the string which doesn't meet the requirements.
The fix is rather simple. Simply remove this limitation as I didn't see any false triggers from this change. Alternatively `[^\(,\s]` can be used instead but I prefer to keep the regex as minimum as possible.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/563)
> linter: Check for namespaces at start of the line

- flake.lock
With the nixpkgs commit our flake is currently locked at, some packages required for the devshell fail to build on `aarch64-darwin`. Updating to the latest version of `nixpkgs-unstable` fixes this. I have also tested building the project and running viking on `x86_64-linux` in the updated devshell and it worked as expected. (I have also updated all other inputs to the flake)
In the future these flake updates should be automated using renovate and a workflow that tests the devshell, but for now, I'll keep PRing lockfile updates when I notice something break
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/580)
> Nix: Fix devshell on darwin by updating the flake lockfile

- lib/al/Library/Yaml/MacroUtil.cpp
- lib/al/Library/Yaml/MacroUtil.h
- lib/al/Library/Yaml/YamlMacroUtil.cpp
- lib/al/Library/Yaml/YamlMacroUtil.h
Who said virtual and templated wasn't allowed. A simple but cursed class that contains each type of yaml object.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/578)
> Library/Yaml: Implement YamlMacroUtil

- lib/al/Project/ArchiveHolder.cpp
- lib/al/Project/ArchiveHolder.h
- lib/al/Project/FileEntryBase.h
Depends on #586. Using a getter for mFileState results in a different optimization taken on `waitLoadDoneAll`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/588)
> Project: Implement `ArchiveHolder`

- lib/al/Project/File/FileLoaderThread.cpp
- lib/al/Project/File/FileLoaderThread.h
Weird pointer to long conversion but hey it works. Depends on #586  required for `FileLoader`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/590)
> Project/File: Implement `FileLoaderThread`

- lib/al/Library/Base/StringUtil.cpp
- lib/al/Library/Base/StringUtil.h
Implements `createFileNameBySuffix`, `outputValueWithComma`, `searchSubString`, `translateCharacters`, `isEqualString` (with safe strings).
Fixes the mismatch in `isEndWithString`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/591)
> Library/Base: Implement a couple functions in `StringUtil`

- lib/al/Library/Audio/AudioDirector.h
Simple fix but important one. Required by `SceneUtil`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/597)
> Library/Audio: Fix `AudioDirector` members

- lib/al/Library/Layout/LayoutActor.h
- lib/al/Library/Nerve/NerveSetupUtil.h
- lib/al/Library/Play/Layout/WipeCloseAppearWaitEnd.cpp
- lib/al/Library/Play/Layout/WipeCloseAppearWaitEnd.h
This PR add `WipeCloseAppearWaitEnd` functions.
The function at `0x710099d5a0` is left unmatching due to a duplicate symbol issue.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/593)
> Library/Play/Layout: Implement `WipeCloseAppearWaitEnd`

- lib/al/Library/Collision/ICollisionPartsKeeper.h
- tools/check-format.py
This is an interface class with only pure virtual functions. Its subclasses are:
- `DynamicCollisionKeeper`
- `anonymous namespace'::SimpleCollisionPartsKeeper`
- `al::CollisionPartsKeeperOctree`
- `al::CollisionPartsKeeperPtrArray`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/608)
> Library/Collision: Add `ICollisionPartsKeeper`

- lib/al/Project/Draw/GpuMemAllocator.cpp
- lib/al/Project/Draw/GpuMemAllocator.h
An unfinished header by @fruityloops1 resulted in me looking into the remaining part of this class - implementing it on the way.
~~Two mismatches can currently be observed:~~
~~1) https://decomp.me/scratch/QhCcn - within `GPUMemBlockT`'s destructor. It was probably wrong before, and is now being exposed because the function is generated for the first time.~~
~~2) https://decomp.me/scratch/nhsZ0 - `al::GpuMemAllocator::allocMemory` shows some slightly different codegen on an `if` with arithmetic.~~
All mismatches have been fixed by @german77 and me!
~~Blocked by https://github.com/open-ead/agl/pull/18~~
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/584)
> Project/Draw: Implement `GpuMemAllocator`

- lib/al/Library/System/SystemKit.cpp
- lib/al/Library/System/SystemKit.h
- lib/al/Project/Resource/ResourceSystem.h
- lib/al/Project/SaveData/SaveDataDirector.h
Mostly straight-forward to implement - `createResourceSystem` took a few tries, especially that block about either instantiating a `SZSDecompressor` or its parallel variant - but everything is matched now.
Requires https://github.com/open-ead/sead/pull/195
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/610)
> Library/System: Implement `SystemKit`

- src/Player/PlayerActionGroundMoveControl.h
Adding another header that is relevant to quite a few `PlayerState`s - this one is responsible for managing grounded movement.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/619)
> Player: Add `PlayerActionGroundMoveControl`

- src/Area/In2DAreaMoveControl.h
- src/Enemy/Togezo2D.cpp
- src/Item/Coin2DCity.cpp
- src/MapObj/BarrelStack2D.cpp
- src/MapObj/FireDrum2D.cpp
- src/MapObj/TransparentWall.cpp
- src/Player/PlayerInput.cpp
- src/Util/ActorDimensionKeeper.cpp
- src/Util/ActorDimensionKeeper.h
- src/Util/ActorDimensionUtil.cpp
- src/Util/ActorDimensionUtil.h
Small helper class that seems like it is used to determine whether switching between 2D/3D mode is possible at any given moment. For this, it also uses areas labeled `2DMoveArea` (which can again be disabled by `IsIgnoreArea`).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/624)
> Util: Implement `ActorDimensionKeeper`

- lib/al/Library/LiveActor/LiveActorKit.cpp
- lib/al/Library/Memory/HeapUtil.cpp
- lib/al/Library/Nerve/NerveSetupUtil.h
- lib/al/Library/Yaml/Writer/ByamlWriterStringTable.cpp
- lib/al/Project/Clipping/ClippingDirector.h
- src/MapObj/AnagramAlphabet.cpp
- src/Sequence/HakoniwaSequence.cpp
- src/System/GameSystem.cpp
- tools/check-format.py
Does exactly what it says on the cover - all warnings are either fixed if the compiler is right to complain about them, or silenced either through workarounds (unused functions referencing "unused" variables = missing code ; `#pragma`s).
https://github.com/open-ead/sead/pull/198 is also needed to fully fix everything, but is independent from this PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/614)
> all: Fix all compiler warnings

- src/Player/PlayerJudgeWallHitDown.cpp
- src/Player/PlayerJudgeWallHitDown.h
- src/Player/PlayerTrigger.h
- src/Util/ObjUtil.h
Another relatively small player judge. This one is responsible for determining whether a specific player action leads to bumping into a wall (damage animation). All of the following checks have to succeed:
- Player must collide with a wall
- The wall must not have `NoAction` type
- PlayerCollisionTrigger value 9 must not be set (?)
- The angle between wall and opposite direction of player (away from wall) must be less than `CollisionHitDownAngleH`, which is 55° by default.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/616)
> Player: Implement `PlayerJudgeWallHitDown`

- lib/al/Library/Execute/ExecuteDirector.cpp
- lib/al/Library/LiveActor/ActorInitUtil.cpp
- lib/al/Library/LiveActor/ActorPoseKeeper.cpp
- lib/al/Library/LiveActor/LiveActorKeeper.cpp
- lib/al/Library/Play/Camera/CameraVerticalAbsorber.cpp
- lib/al/Library/Rail/Rail.cpp
- lib/al/Library/Yaml/ByamlData.cpp
- lib/al/Library/Yaml/ByamlHeader.cpp
- lib/al/Library/Yaml/ByamlIter.cpp
- lib/al/Library/Yaml/Writer/ByamlWriter.cpp
- lib/al/Project/Item/ActorScoreKeeper.cpp
- lib/al/Project/Rail/BezierCurve.cpp
- lib/al/Project/Rail/LinearCurve.cpp
- src/Npc/FukuwaraiFaceParts.cpp
- src/Player/Player.cpp
- src/System/GameDataFile.cpp
This PR adds `decomp.me` links to all existing `NON_MATCHING` comments as suggested in #71. I've also removed three `NON_MATCHING` comments from matching functions. All of these `decomp.me` scratches have been auto generated by the version of the `decompme` tool from open-ead/nx-decomp-tools#31 without any modifications (although I have checked that each scratch compiles fine)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/627)
> All: Add decomp.me links to NON_MATCHING comments

- src/Player/PlayerStateDamageLife.cpp
- src/Player/PlayerStateDamageLife.h
- src/Player/PlayerTrigger.h
- src/Util/ObjUtil.h
- src/Util/PlayerCollisionUtil.h
Contrary to what the name suggests, this state does not only trigger when the player receives damage, but also when bonking into a wall - see #616 here.
Apart from that, here are some other possibly interesting facts:
- When the player is in 2D mode, this state only lasts for a single frame
- The player can be forced into a squat after damage, if the ceiling is not high enough to stand up
- The state can be canceled after landing on the ground for the first time, and waiting another `DamageCancelFrame` frames (default: 45)
- This state is usually lasts until the player falls onto the ground (=> Land) and for the duration of the `DamageLand` animation (78 frames), but as stated before, can be canceled 45 frames after landing or is automatically stopped after falling for 120 frames
- If the …
> Player: Implement `PlayerStateDamageLife`

- src/Util/ActorDimensionKeeper.h
- src/Util/ActorDimensionUtil.cpp
- tools/check-format.py
This PR adds a linter check that requires the names of header defined boolean getters to be prefixed with `is` or `has` (or `get_` for offset named variables). Because all of the getters that needed to be renamed where in `ActorDimensionKeeper`, this PR uses #624 as a base and should wait for that PR to be merged first (although the linter check should be ready for review)
Fixes #443
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/625)
> Custom linter: enforce `is`/`has` prefix for inlined boolean getters

- lib/al/Library/Execute/ActorExecuteInfo.h
- lib/al/Library/Execute/ExecuteRequestKeeper.cpp
- lib/al/Library/Execute/ExecuteRequestKeeper.h
- lib/al/Library/Execute/ExecutorActorExecuteBase.h
Weird way to implement this keeper. `ExecuteRequestKeeper::request` has a potential out of bounds write. `ExecuteRequestTable` can add more elements than the array size.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/630)
> Library/Execute: Implement ExecuteRequestKeeper

- lib/al/Library/Clipping/ClippingActorHolder.h
- lib/al/Library/Clipping/ClippingActorInfo.h
- lib/al/Library/Clipping/ClippingActorInfoList.cpp
- lib/al/Library/Clipping/ClippingActorInfoList.h
- lib/al/Library/Clipping/ClippingGroupHolder.h
- lib/al/Library/Clipping/ClippingInfoGroup.h
- lib/al/Library/LiveActor/ActorInitInfo.cpp
- lib/al/Library/LiveActor/ActorInitUtil.cpp
- lib/al/Project/Clipping/ClippingDirector.cpp
- lib/al/Project/Clipping/ClippingDirector.h
- lib/al/Project/Clipping/ViewInfoCtrl.cpp
- lib/al/Project/Clipping/ViewInfoCtrl.h
More effort went into the headers than the actual implementation. Headers conflict with #521 and #570
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/582)
> Library/LiveActor: Implement `ActorInitInfo`

- src/Player/PlayerActionGroundMoveControl.h
- src/Player/PlayerInput.h
- src/Player/PlayerStateGroundSpin.cpp
- src/Player/PlayerStateGroundSpin.h
The name is pretty clear on what this state is doing: Spin the player while grounded.
Its implementation is also mostly straight-forward. Only one notable thing:
- the direction of a spin (clockwise/counter-clockwise) only changes the animation and does not affect anything else
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/646)
> Player: Implement `PlayerStateGroundSpin`

- lib/al/Library/Memory/HeapUtil.cpp
- lib/al/Library/Memory/HeapUtil.h
- lib/al/Project/Memory/MemorySystem.cpp
- lib/al/Project/Memory/MemorySystem.h
- lib/al/Project/Memory/SceneHeapSetter.h
- lib/al/Project/Memory/Util.h
This class is used to manage heaps for storing all data related to a specific scene, and clearing the heaps when unloading an area. Particularly notable are the hardcoded sizes for the different heap types. Replacing these functions would allow easy adjustment of these for modders.
One mismatch is introduced in this PR:
https://decomp.me/scratch/Pqb4H
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/648)
> Project/Memory: Implement `MemorySystem`

- tools/setup.py
As mentioned in open-ead/nx-decomp-tools#30, `nx2elf` has builtin functionality for NSO decompression and the usage of `hactool` is unnecessary. This PR removes the usage of `_decompress_nso` from `setup.py`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/623)
> Setup: Remove usage of `hactool` for NSO decompression

- .github/scripts/copy-headers.sh
- .github/scripts/process-headers.py
- .github/workflows/copy-headers.yml
- .github/workflows/progress.yml
This PR simplifies the progress worklow by removing setting up and building the project from it. I also made it so that `copy-headers.sh` removes lines with `inline` functions from the `al` and `game` folders that don't appear in the executable since calling them would cause a crash
I have tested the `inline` function remover inside a local copy of the headers repo but not the progress workflow
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/343)
> Workflow: simplify `progress.yml` and remove unusable `inline` functions from headers repo

- tools/build.py
- tools/setup.py
This PR makes it so that `build.py` prints a warning if the `CACHE_REPO_RELEASE_URL` in `setup.py` does not match the cached url
Fixes #678
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/679)
> build.py: Print recomendation to update tools if they are outdated

- lib/al/Library/MapObj/ConveyerStep.cpp
- lib/al/Project/LiveActor/ConveyerKeyKeeper.cpp
- lib/al/Project/LiveActor/ConveyerKeyKeeper.h
`al::ConveyerKeyKeeper::calcPosAndQuat`, `al::ConveyerKeyKeeper::calcPosAndQuatByIndex` and `al::ConveyerKeyKeeper::calcClippingSphere` all share the same mismatch: https://decomp.me/scratch/4dAST
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/680)
> Project/LiveActor: Implement `ConveyerKeyKeeper`

- .github/scripts/process-headers.py
More stuff being broken: The workflow doesn't like if macros end with a `inline` function definition, without body. In that case, it apparently keeps searching until the next "ending token" is found (semicolon or some brace type at the end of a line).
This fix is not particularly nice, but works: Just stop and ignore if an empty line is found. This should never happen in function declarations, which is all we're searching for here. The better option would be to find the closing parenthesis of the function parameters, but ... that's annoying, especially given that more parentheses might be used within the function parameter types (function pointers, ...).
- - - …
> workflows: Fix more `inline` functions for macro definitions in OdysseyHeaders

- .github/scripts/process-headers.py
Another one. See the comment above the newly-added special case for a reasoning:
```py
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/706)
> workflow: Still fix `inline` functions for SensorMsg macros in OdysseyHeaders

- src/Player/PlayerStateLongJump.cpp
- src/Player/PlayerStateLongJump.h
- src/Util/ObjUtil.h
Another player state. Interesting facts about this one:
- shares most of its movement code with the dive, so controls feel very similar on them
- For the `E3` demo, the jumping animation was hardcoded to `JumpBroad3`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/701)
> Player: Implement `PlayerStateLongJump`

- src/Player/PlayerStateNormalWallJump.cpp
- src/Player/PlayerStateNormalWallJump.h
Apparently, there is a flag that avoids flipping horizontal velocity after a wall jump, directing it into the wall instead. No idea where that is supposed to be used, I didn't find anything setting this variable to `true`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/708)
> Player: Implement `PlayerStateNormalWallJump`

- lib/al/Library/Effect/EffectKeeper.h
This file contains some wrong/missing return types, and two functions are not marked as `const` correctly.
Noticed by @mcanterogomez, thanks!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/709)
> Effect: Fix function signatures in `EffectKeeper`

- lib/al/Library/LiveActor/LiveActorFlag.h
As it turns out, our logic is flipped here. This variable is not used anywhere yet, so it didn't become obvious in any function.
Found this in a debugging session in cooperation with @mcanterogomez.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/717)
> Library/LiveActor: Fix name of `LiveActorFlag->isModelHidden`

- lib/al/Library/HitSensor/SensorMsgSetupUtil.h
- lib/al/Library/LiveActor/ActorSensorUtil.cpp
- lib/al/Library/LiveActor/ActorSensorUtil.h
This PR does some refactoring to the stuff added in #415 based on what I noticed while implementing game `SensorMsg` stuff.
The following changes were made:
* Since `SEND_MSG_WITH_DATA_MULTI_IMPL` already supports just giving it one data field, I renamed it to `SEND_MSG_WITH_DATA_IMPL` and removed the old `SEND_MSG_WITH_DATA_IMPL` macro. This forces all invocations of the macro to be given proper field names for the data even if there's only one field which is good for keeping the naming consistent between the header and cpp because we probably don't want to name the params in the header `data`
* Similarly I changed `SEND_MSG_DATA_TO_ACTOR` so that it now takes a name for the data field instead of just using `data` as the name
* Function param names now match between …
> Library/HitSensor: Refactor `SensorMsg` related macros and functions

- lib/al/Library/LiveActor/ActorSensorUtil.cpp
In #415, one of the functions I added was `isCrossoverSensor`. I do remember adding this function to the csv, but I think what happened was that when the new file list format was added, I just used the upstream file list and ran `tools/check`, losing the added symbol. This function was also mismatching. These things also explain why while I was fixing the final things of that PR, I thought I remembered that there had been one more mismatching function to fix.
So this PR adds that function to the file list and also fixes the small logic issue in my implementation of it (thanks to @german77 for identifying that logic issue)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/Od …
> `Library/LiveActor/ActorSensorUtil`: Fix `isCrossoverSensor`

- lib/al/Library/Clipping/ClippingGroupHolder.cpp
- lib/al/Library/Clipping/ClippingGroupHolder.h
It turns out that ClippingInfoGroup was a struct. Kinda makes sense based on the name. ClippingGroupHolder might be a struct but ill change that if I run into something that hints to that later on.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/686)
> Library/Clipping: Implement `ClippingGroupHolder`

- lib/al/Library/Rail/Rail.h
- lib/al/Library/Rail/RailRider.h
- lib/al/Library/Rail/RailUtil.cpp
- lib/al/Library/Rail/RailUtil.h
Utility functions for `Rail`-related objects.
`al::calcRailPosFront` and `al::calcRailDirFront` have the same mismatch: https://decomp.me/scratch/0vmMR
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/703)
> Library/Rail: Implement `RailUtil`
